### ISSUE TITLE
Wrong handling of utcoff

### ISSUE THREAD

**Issue by Cigaes** [time-rs/time#116]
The code to handle the utcoff looks like this:

``` rust
        let sec = match self.tm_utcoff {
            0 => sys::utc_tm_to_time(self),
            _ => sys::local_tm_to_time(self)
        };
```

And `local_tm_to_time()` is a wrapper around `mktime()`. Unfortunately, `mktime()` does not use the `gmtoff`/`utcoff` field, it always use the system timezone for the process.

(There is a reason for that: the `gmtoff`/`utcoff` field is not standard, and the standard does not require to init the structure to 0 as a whole, so conforming applications could feed uninitialized memory for this field.)

The gist of it is that the libc functions are unusable to handle timezones correctly without quite a bit of effort from the application. A wrapper library needs to either document that usability issue or implement work-arounds.

(As a side note, your re-implementation of `timegm()` is not thread-safe.)

**Comment by PeterReid** [comment]
I ran into this as well when I was doing some time zone manipulation and fixed it (at least such that it worked for what I needed) here. https://github.com/PeterReid/time/commit/e0ce2fd4c89028c2378612f53b080ddb889a22ec

Making utcoff significant exposed an existing bug where the Windows implementation sets utfoff incorrectly, which complicated the change some.

**Comment by dten** [comment]
I have this and corrected it similarly to @PeterReid in a local build. The test_time_sub was failing when on BST
