### ISSUE TITLE
Allow stripping of leading space with "%-"

### ISSUE THREAD

**Issue by chrismiddleton** [time-rs/time#129]
It would be useful to be able to use `strftime` without the leading space that is inserted for certain modifiers. In particular, the hour. Doing a `man strftime` shows it's a GNU libc extension. My use case:

```
// would print "The time is 4:38 PM", currently causes "InvalidFormatSpecifier('-')"
println!("The time is {}", time::now().strftime("%-l:%M %p").unwrap());
```

**Comment by jhpratt** [comment]
It is my intent to support this in v0.2.

**Comment by jhpratt** [comment]
Done!
