### ISSUE TITLE
Timezones discarded in time::Tm methods

### ISSUE THREAD

**Issue by afandian** [time-rs/time#135]
I can't seem to get any kind of absolute date from a `Tm`. Here's two with different timezone offsets:

```
let a = Tm { tm_sec: 01, tm_min: 01, tm_hour: 12, tm_mday: 1, tm_mon: 0, tm_year: 113, tm_wday: 2, tm_yday: 0, tm_isdst: 0, tm_utcoff: -18000, tm_nsec: 0 };
let b = Tm { tm_sec: 01, tm_min: 01, tm_hour: 12, tm_mday: 1, tm_mon: 0, tm_year: 113, tm_wday: 2, tm_yday: 0, tm_isdst: 0, tm_utcoff: 0, tm_nsec: 0 };

println!("a == b {}", a == b);
println!("a.to_utc() == b.to_utc(): {:?}", a.to_utc() == b.to_utc());
println!("a.to_local() == b.to_utc(): {:?}", a.to_local() == b.to_local());
println!("a.to_timespec() == b.to_timespec(): {:?}", a.to_timespec() == b.to_timespec());
```

Gives

```
a == b false
a.to_utc() == b.to_utc(): true
a.to_local() == b.to_utc(): true
a.to_timespec() == b.to_timespec(): true
```

All these functions seem to discard the timezone info.

**Comment by jugglerchris** [comment]
Hi,
I've just found that timezone offsets are ignored too.  Would a PR which either fixed this, or at least updated the documentation to say they're broken, be accepted?  I can and will move my projects to chrono now, but it'd be nice to avoid anyone else silently getting the wrong answers!

Thanks!

**Comment by jhpratt** [comment]
Closing this, as the `Tm` struct will not exist in 0.2. There will be `DateTime` and `OffsetDateTime` structs, which will correctly implement equality and offset conversions.
