### ISSUE TITLE
`Tm::tm_yday` is completely wrong in Windows

### ISSUE THREAD

**Issue by lifthrasiir** [time-rs/time#137]
Discovered while debugging lifthrasiir/rust-chrono#85. `time::sys::inner::system_time_to_tm` contains [this piece](https://github.com/rust-lang-deprecated/time/blob/4c81709/src/sys.rs#L398-L407) of code:

``` rust
        fn yday(year: i32, month: i32, day: i32) -> i32 {
            let leap = if month > 2 {
                if year % 4 == 0 { 1 } else { 2 }
            } else {
                0
            };
            let july = if month > 7 { 1 } else { 0 };

            (month - 1) * 30 + month / 2 + (day - 1) - leap + july
        }
```

...which will give the number of days in each month as `31, if year % 4 == 0 { 29 } else { 28 }, 31, 30, 31, 30, 32, 30, 31, 30, 31, 30`---completely wrong for some centurial years like 1900 (rare) and August and later (extremely common).

**Comment by jhpratt** [comment]
This will not be an issue in v0.2.
