### ISSUE TITLE
Add deprecation(?) notice to documentation?

### ISSUE THREAD

**Issue by sector-f** [time-rs/time#146]
Currently the repo's readme says "In case you're looking for something a little fresher and more actively maintained have a look at the chrono crate."

Would it perhaps be a good idea to put a similar note in the module documentation?

**Comment by RalfJung** [comment]
Indeed that would have been nice, I may not have wated time using this create had I known there is a better alternative... somehow, this one turned up first on Google.

**Comment by vks** [comment]
I think the deprecation warning should go to the description on crates.io.

**Comment by luukvanderduim** [comment]
Would you know  - if 'time' ends up being deprecated - where or if one could find the convenience of PreciseTime and associated methods?
