### ISSUE TITLE
Duration::span should also return the return value of the closure

### ISSUE THREAD

**Issue by gnzlbg** [time-rs/time#167]
Currently `Duration::span` only returns a `Duration` but it should also return the return value of the closure (otherwise it is lost).

**Comment by gnzlbg** [comment]
Why was this issue closed?

**Comment by jhpratt** [comment]
@gnzlbg I'm currently working on v0.2, which will return a tuple of the time and value. It's already done on the master branch.

**Comment by gnzlbg** [comment]
thanks, glad to see the pace picking up here, I thought this crate was in maintenance mode only
