### ISSUE TITLE
Tm::PartialEq inconsistent with Tm::PartialOrd

### ISSUE THREAD

**Issue by nwalfield** [time-rs/time#180]
Consider the following [code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=81e83d5ebf30cdefd21ef4d0b73d754f):

```
fn main() {
    let t1 = time::Tm { tm_sec: 0, tm_min: 0, tm_hour: 0, tm_mday: 1, tm_mon: 0, tm_year: 101, tm_wday: 0, tm_yday: 0, tm_isdst: 0, tm_utcoff: 0, tm_nsec: 0 };
    let t2 = time::Tm { tm_sec: 0, tm_min: 0, tm_hour: 0, tm_mday: 1, tm_mon: 0, tm_year: 101, tm_wday: 1, tm_yday: 0, tm_isdst: 0, tm_utcoff: 0, tm_nsec: 0 };
    
    println!("t1 == t2: {:?}", t1 == t2);
    println!("t1.cmp(&t2): {:?}", t1.cmp(&t2));
}
```

t1 and t2 are identical modulo the tm_wday field.

When using PartialEq to compare t1 and t2, the result is false.  When using PartialOrd, the result is Ordering::Equal.

```
t1 == t2: false
t1.cmp(&t2): Equal
```

This inconsistency is a bug.

I'd argue that the PartialOrd behavior is correct, because they are both the same time (wday is derived and, I guess, whatever generated t1 didn't bother to fill in wday).

Looking at the [source code](https://docs.rs/time/0.1.42/src/time/lib.rs.html#298), this appears to happen, because PartialEq is derived and PartialOrd is implemented by converting to a timespec and then comparing that.

**Comment by jhpratt** [comment]
Closing as this won't be an issue in v0.2. The `Tm` struct will be replaced by a full `DateTime`, and the `Date` component has `weekday` as a method, not a field.
