### ISSUE TITLE
Bug: Could not build on Redox

### ISSUE THREAD

**Issue by FloVanGH** [time-rs/time#183]
I could not built time for redox

` /home/florian/.cargo/registry/src/github.com-1ecc6299db9ec823/time-0.1.42/src/sys.rs:351:1
    |
138 | mod inner {
    | --------- previous definition of the module `inner` here
...
351 | mod inner {
    | ^^^^^^^^^ `inner` redefined here
    |
    = note: `inner` must be defined only once in the type namespace of this module
`

I think this is because the rust compiler recognizes Redox now as unix. There was on pull request to add redox to the unix family some weeks ago.

**Comment by jhpratt** [comment]
Closing this, as v0.1 is basically dead. Unless @alexcrichton would like to merge the PR and create a new point release?

I'm working on v0.2, which will be based entirely on `std::time`. As such, it should compile as expected on Redox.
