### ISSUE TITLE
Wasm support

### ISSUE THREAD

**Issue by mankinskin** [time-rs/time#184]
System time is currently unimplemented for `target_arch="wasm32"`: https://docs.rs/time/0.1.42/src/time/sys.rs.html#102

When compiling to wasm32, I currently have to use stdweb and get the system time through javascript: https://docs.rs/stdweb/0.4.19/stdweb/web/struct.Date.html#method.get_time

Does anyone have more information about how to get the system time from wasm directly?

**Comment by jhpratt** [comment]
wasm should be fully supported in v0.2, which is currently in progress. I believe everything on the master branch currently works with wasm, though it's not part of the build checks — I should probably add that!

Note that it'll still be more efficient byte-wise to pass it through to JavaScript, but that's your concern.

**Comment by jhpratt** [comment]
Now that I think about this, it's not really possible to add wasm to the full build process without including tons of other things. I could always ensure it compiles when targeting wasm and not run the test suite, but that wouldn't be terribly useful.

Closing as not particularly actionable, aside from the already-in-progress v0.2.
