### ISSUE TITLE
Sunday and Monday-based week numbering

### ISSUE THREAD

**Issue by jhpratt** [time-rs/time#186]
I'm unable to find any references for algorithms to calculate the Sunday or Monday-based week number from an ordinal day and vice versa. If you have found such a reference (either in print or online), please respond with such. I'll happily implement this, which would be useful for those in North America, primarily.

**Comment by hhamana** [comment]
This is implemented in the `chrono` crate.
https://github.com/chronotope/chrono

The whole Rust environment is switching to that create for more advanced time management.

**Comment by jhpratt** [comment]
@hhamana I am aware of chrono. The Rust community has basically switched over to chrono _because_ the time crate was unmaintained for years. The current implementation of time (on crates.io) predates the standard library! Chrono is actually based on that, which creates some odd interoperability issues. Time will resolve that and also add some additional functionality.

Setting aside the differences (which I'll expand upon prior to a 0.2 release), I will certainly take a look over there to see if they're handling the calculation in a manner similar to that I can use.

**Comment by jhpratt** [comment]
Mostly posting this for myself so I don't forget.

A quick search reveals it may be as simple as I suspected — subtracting the weekday number and dividing is sufficient. It may be worthwhile to verify this exhaustively, but I presume [chrono's implementation](https://github.com/chronotope/chrono/blob/9e50bfe03460036dbd752440851d924be3730b08/src/format/mod.rs#L370-L374) is accurate.

**Comment by hhamana** [comment]
`chrono` implements this through an enum, returning the day number through custom functions for the chosen ordering. It wouldn't be hard to do it yourself if you want to, indeed.
