### ISSUE TITLE
Ended up here trying to find out why our project had a dependency on winapi

### ISSUE THREAD

**Issue by stevenroose** [time-rs/time#189]
Great news that v0.2 no longer has a winapi dependency. Any ETA on a release?

**Comment by jhpratt** [comment]
My goal is to have time v0.2 released alongside 1.40, which is [scheduled for release] on December 19. It will have zero mandatory runtime dependencies.

If you're using beta, the crate is usable via git now (though some changes may be made before release).

**Comment by stevenroose** [comment]
"using beta".. What will be the MSRV for time v0.2? Is there a MSRV right now? If you'd be open to this, I could add some Travis builds that ensure compilation for certain Rust versions.

**Comment by jhpratt** [comment]
1.40 is the MSRV for v0.2. That is the current beta. The CI already ensures everything works on that, and once it's released, I'll modify it to check on both 1.40 and the most recent stable.

**Comment by jhpratt** [comment]
@stevenroose You may be interested in #190.
