### ISSUE TITLE
Overflow panic! in precise_time_ns() 

### ISSUE THREAD

**Issue by ZiCog** [time-rs/time#192]
One of my Rust experiments, which had been working well for ages, surprised me by not starting this morning. Producing a panic that I can reproduce as follows:

The code:
```
$ cat src/main.rs
use time::precise_time_ns;

fn main() {
    let start_time = precise_time_ns();

    println!("{}", start_time);
}
```
The result:
```
$ rustup default stable
info: using existing install for 'stable-x86_64-unknown-linux-gnu'
info: default toolchain set to 'stable-x86_64-unknown-linux-gnu'

  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.39.0 (4560ea788 2019-11-04)

$ cargo clean
$ cargo run
   Compiling libc v0.2.66
   Compiling time v0.1.42
   Compiling rust_time_bug v0.1.0 (/mnt/c/Users/michael/rust_time_bug)
    Finished dev [unoptimized + debuginfo] target(s) in 5.62s
     Running `target/debug/rust_time_bug`
thread 'main' panicked at 'attempt to multiply with overflow', /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/time-0.1.42/src/sys.rs:581:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Running on Debian Buster.

**Comment by ZiCog** [comment]
Forgot to mention. This is Debian Buster running inside the Windows Subsystem For Linux on Win 10.

I rebooted the machine an sure enough every thing is working fine again.

**Comment by jhpratt** [comment]
Looks like you're using v0.1? A full rewrite is in progress, so running the same code on master should work (it's deprecated, though).

**Comment by ZiCog** [comment]
After some googling around it appears that this is a problem with the Windows Subsystem for Linux.
https://github.com/microsoft/WSL/issues/3840

When I patched a println! into the time crate I found both tv_sec and tv_nsec were negative!
```
        pub fn get_precise_ns() -> u64 {
            let mut ts = libc::timespec { tv_sec: 0, tv_nsec: 0 };
            unsafe {
                libc::clock_gettime(libc::CLOCK_MONOTONIC, &mut ts);
            }
            println!("ts.tv_sec = {}", ts.tv_sec);
            println!("ts.tv_nsec = {}", ts.tv_nsec);
            (ts.tv_sec as u64) * 1000000000 + (ts.tv_nsec as u64)
        }
```
I don't know if time-rs can be made to tolerate that.

**Comment by jhpratt** [comment]
Given that (1) it's a bug in the subsystem and (2) a full rewrite is in progress and should be released in just over two weeks, I'm going to close this as a wontfix.

I see that you mentioned on the users forum that you were timing something. I recommend using [`Duration::span`](https://docs.rs/time/0.1.42/time/struct.Duration.html#method.span) in v0.1 or [`Duration::time_fn`](https://time-rs.github.io/time/time/struct.Duration.html#method.time_fn) in v0.2.

**Comment by ZiCog** [comment]
OK. Sounds good.

Yes, using span or such would be better. What I have now only came about because it started out as more or less direct translation of some C code that used clock_gettime().

Sorry for the bother. Thanks.

**Comment by jhpratt** [comment]
Not an issue! If 0.1 were fully supported and maintained, I'd likely have at least attempted to hack something up as a temporary fix. As long as everything is in good faith, I'll respond in the same :slightly_smiling_face:
