### ISSUE TITLE
Yank breaking versions with "*" deps

### ISSUE THREAD

**Issue by kornelski** [time-rs/time#194]
Some old versions of `time` have dependencies specified with `"*"` version requirement (`gcc = "*"`).

Crates with such vague dependency versions became unusable, because `*` allows picking too-new semver-incompatible dependencies.
It also breaks Cargo's `minimal-versions` feature, because `*` requirement allows picking very very old dependencies that aren't compatible with Rust 1.0.

Because these old versions of `time` are unusable and cause problems for Cargo, I suggest yanking them:

```bash
cargo yank --vers 0.0.1
cargo yank --vers 0.0.2
cargo yank --vers 0.0.3
```

**Comment by jhpratt** [comment]
I'll likely yank them once I gain access on crates.io (hopefully within the coming weeks). Anyone that is still relying on those for whatever reason can deal with the warning — I imagine they won't mind if they're using a compiler that old.

Is it just those three versions, or were those just used as an example?

**Comment by kornelski** [comment]
Just these use `"*"` deps.

**Comment by jhpratt** [comment]
Alright, will do when I'm able.

**Comment by jhpratt** [comment]
All three versions in question have been yanked.
