### ISSUE TITLE
How does one upgrade from time 0.1 to time 0.2?

### ISSUE THREAD

**Issue by YorickPeterse** [time-rs/time#197]
Version 0.1 of the `time` crate provided a pretty bare-bones API, but it made it easy to create a generic time structure that didn't care if the wrapped time was in UTC, local time, or something else. This was due to the result being a `Tm` struct, instead of a different type based on whether you were using local time or UTC.

Version 0.2 seems pretty different from this approach, which on first sight seems to make it difficult to migrate from version 0.1. This is best illustrated with some actual code, which can be found here: https://gitlab.com/inko-lang/inko/blob/f668bbe2580aa6f2e12f3bb41eafe252efd3ed7b/vm/src/date_time.rs

The `DateTime` struct in this file is meant as a very basic type to store the current time, either using the local timezone or UTC. This type is mostly used as an intermediate type to convert the raw `Tm` struct into a number. Since this project is a VM and language, we don't need more complex types, as the language has its own time library implementation (built around timestamps), which can be found here: https://gitlab.com/inko-lang/inko/blob/f668bbe2580aa6f2e12f3bb41eafe252efd3ed7b/runtime/src/std/time.inko. The `DateTime` type is also used for some filesystem operations, but those too are all converted to just numbers.

Looking at 0.2 of the `time` crate, it seems to only support times using UTC as the timezone, with seemingly no support for local time. We could use Rust's `SystemTime` type for local time, but there does not appear to be a way of converting this to just a Unix timestamp. Similarly, time's own `Time` type also does not appear to support obtaining the number of seconds since the Unix epoch. All of this looks like it will make it difficult to upgrade from 0.1, unless I am missing something.

Specifically, I am interested in learning more about what one could best do to replace the following APIs that were provided by `time` 0.1:

* `time::now()`
* `time::now_utc()`
* `time::at()`
* `Tm::tm_isdst`, this was used to check if DST is active or not on the local clock
* `Tm::to_timespec()`, this was used to construct a Unix timestamp in seconds

**Comment by YorickPeterse** [comment]
One option is to use an enum that wraps `std::time::SystemTime` and `time::Time`, but I can see this getting messy quickly

**Comment by YorickPeterse** [comment]
Per the Matrix chat, it seems `time::now()` could be replaced by more or less the following:

```rust
use std::time::SystemTime;
use time::PrimitiveDateTime;

let prim = PrimitiveDateTime::from(SystemTime::now());
```

You can then get the Unix timestamp using `PrimitiveDateTime::timestamp()`.

**Comment by YorickPeterse** [comment]
`time::now_utc()` would in turn be replaced by `PrimitiveDateTime::now()` by the looks of it.

**Comment by YorickPeterse** [comment]
`time::at()` would be replaced by `PrimitiveDateTime::from_unix_timestamp()`, which takes an `i64`.

**Comment by jhpratt** [comment]
Time v0.2 definitely takes a very different approach than v0.1. Time zones are not actually supported, rather just UTC offsets for now — full tzdb support is planned.

`time::now()` and `time::now_utc()` can be replaced with `OffsetDateTime::now()` (or other types as needed). Currently, this will _always_ return the offset as UTC, though that may change in the future.

`time::at()`, `Tm::tm_isdst()`, and `Tm::to_timespec()` all need info about the system's local timezone and/or offset, which is not currently possible. This will likely be added in a future version.

**Comment by YorickPeterse** [comment]
`Tm::to_timespec()` for my particular case (obtaining the Unix timestamp) can be replaced by `PrimitiveDateTime::timestamp()`

**Comment by jhpratt** [comment]
With regard to getting the system's UTC offset and DST, it looks like this is possible while using libc for Unix and winapi for Windows. This may be gated under a `local` feature. I don't have experience with C's datetime APIs, so I'll probably have some digging to do to figure out the exact parameters necessary to pass.

I'm going to investigate how hard it'll be to add in, though it's not my priority currently.

**Comment by hotel-dieu** [comment]
I know that programmers and scientists like to give narrow and uncommon meanings to words, but for the rest of us, "time" refers to "local time", not "UTC time". Can you imagine asking someone in the street "What time is it?", and him answering: "It's 23 UTC". Or telling a friend or a collegue: "Meet me at the coffeeshop at 16 UTC". You might as well go drink that coffee alone. Sorry, but I don't live in Greenwich, and I don't have the slightest clew what my offset is relative to Greenwich. If I knew such details, I wouldn't be using a "time" crate in the first place.

(Sorry if I am being sarcastic. The migration from "time" 0.1 to "time" 0.2 is proving a nightmare for me.)

**Comment by jhpratt** [comment]
@hotel-dieu Is there a question you have?

If you're trying to obtain the local offset, you have to be patient. Trying to cover most systems is surprisingly difficult. If you'd like me to change the behavior to return the local time by default, that will not happen. Behavior should be consistent between various systems — my intent to have nothing implicitly depend on the system's UTC offset is documented in a number of places.

**Comment by hotel-dieu** [comment]
"time" 0.1 allowed me to get the local time, and did it flawlessly. I guess I am just disconcerted that "time" 0.2 isn't able to do the same. Granted, I have not looked under the hood: maybe the new clock wiring is more advanced and more accurate than ever. But for now, all I'm seeing is that the clock's hand is not pointing at the right hour.

(Sorry if I am being negative. I will just hardcode the offset, and get it over with. I'm an early adopter of a new version. All things improve over time, especially a "time" crate.)

**Comment by kentfredric** [comment]
> "time" 0.1 allowed me to get the local time, and did it flawlessly. I guess I am just disconcerted that "time" 0.2 isn't able to do the same. Granted, I have not looked under the hood: maybe the new clock wiring is more advanced and more accurate than ever. But for now, all I'm seeing is that the clock's hand is not pointing at the right hour.
> 
> (Sorry if I am being negative. I will just hardcode the offset, and get it over with. I'm an early adopter of a new version. All things improve over time, especially a "time" crate.)

This somewhat sounds like you have code possibly doing date math using local time, which while understandable, is strongly not recommended, for messy and complicated reasons ( DST changing in the middle of your date math for instance, doesn't help ).

If at all possible, you should be using UTC internally, and then converting to localtime for presentation only.

**Comment by dalcde** [comment]
I have the same issue, and my use case is extremely simple - format and print the current (local) date and time. I'm currently sticking with time 0.1. Would be grateful to learn of a way to do this concisely with time 0.2.

**Comment by jhpratt** [comment]
@dalcde Thanks for your comment. I am currently working on basic macros, then I'm definitely going to take a look to see what's possible!

**Comment by jhpratt** [comment]
@dalcde If you've got any experience with OS APIs, you may be interested in #203.

**Comment by jhpratt** [comment]
Pretty much the only reason this issue was open was due to the ability to have local offsets, which is being tracked in #203. Everything else should be sufficiently explained by various documentation.
