### ISSUE TITLE
No way to validate a Time format string

### ISSUE THREAD

**Issue by osa1** [time-rs/time#198]
In 0.1 era `srtftime` used to return an error when format string is not valid, which is removed in the current `Time::format`. This makes it hard to get a format string from the user (context: https://github.com/osa1/tiny/pull/163).

It'd be good to either return an error (instead of panicking) or provide a validation function for format strings.

**Comment by jhpratt** [comment]
I could provide a function that returns a boolean indicating if a formatting string is valid. In almost all cases, though, an incorrect formatting string is a programmer error, which is why I opted for a panic.

Look for this being on master within a couple days!

**Comment by osa1** [comment]
> boolean indicating if a formatting string is valid

Could you return a string describing the problem, instead of a bool? It seems like you already have a string (shown in the panic message).

**Comment by jhpratt** [comment]
Sure, that's doable as well. If you're using the standard library, you could actually capture the panic message now. That's obviously far from ideal, though.

**Comment by jhpratt** [comment]
Implemented on master. There's a method with the signature `fn validate_format_string(s: &str) -> Result<(), String>`.

Is this for a private binary, or is this a crate that would need a new release on crates.io? If the latter, I can definitely do so.
