### ISSUE TITLE
Please document reasons for yanked versions

### ISSUE THREAD

**Issue by shepmaster** [time-rs/time#204]
There's no description of why 0.2.3 was yanked. As a [user of 0.2.3](https://github.com/integer32llc/rust-playground), I don't know if there's an issue with that release that I need to fix and deploy immediately or not

I attempted to read the CHANGELOG, but there doesn't appear to be one. The newest [release](https://github.com/time-rs/time/releases) is 0.2.3, which is probably another issue.

**Comment by jhpratt** [comment]
Yeah, sorry about that! 0.2.3 had the breaking change, which was reverted in 0.2.4 — turns out it didn't have to be made in the first place, and I read serde's docs wrong.

I was aware of hadn't updated the GitHub releases, and plan on doing that later today.

**Comment by jhpratt** [comment]
Done! For reference, v0.2.4 is backwards-compatible with v0.2.2.

Hopefully this didn't cause too much issue :slightly_smiling_face:
