### ISSUE TITLE
`is_positive` and `is_negative` methods for `Duration`

### ISSUE THREAD

**Issue by fooker** [time-rs/time#208]
Seems like there is no easy way to determine if a `Duration` is positive or negative beside comparing with `Duration::zero()` or checking `Duration::num_seconds()`.

Use-cases for this are:
* Checking if a `Duration` is convertible to `std::time::Duration`
* Checking if a `DateTime` is before or after another while calculating the remaining time

Such methods could simply compare with `self.secs` as `Duration::to_std` does.

**Comment by jhpratt** [comment]
I'm assuming you closed this because you found it yourself, but for anyone else running across this, there are `is_positive`, `is_negative`, and `is_zero` methods already :slightly_smiling_face:

**Comment by fooker** [comment]
Exactly. I was coming from chrono, which just uses an old version of time.
