### ISSUE TITLE
docs require a nightly build

### ISSUE THREAD

**Issue by andrewtj** [time-rs/time#210]
It seems rustdoc as of 1.41.0 fails to build:

```
$ rustdoc --version
rustdoc 1.41.0 (5e1a79984 2020-01-27)
```

```
$ cargo doc
 Documenting time v0.2.6
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> /home/atj/.cargo/registry/src/github.com-1ecc6299db9ec823/time-0.2.6/src/lib.rs:124:18
    |
124 | #![cfg_attr(doc, feature(doc_cfg))]
    |                  ^^^^^^^^^^^^^^^^

error: Compilation failed, aborting rustdoc

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0554`.
error: Could not document `time`.

````

**Comment by jhpratt** [comment]
Hmm...I suppose I could enable the feature only on nightly. Unfortunately it would be missing some pretty significant annotations, and intra-doc links would no longer work. I suppose something is better than nothing, though?

I'll likely get to this within a day or two, as it should be pretty easy to do. Given that docs are still available both online and able to be built with nightly, I'll hold off on a 0.2.7 release for now.

**Comment by andrewtj** [comment]
> Hmm...I suppose I could enable the feature only on nightly. Unfortunately it would be missing some pretty significant annotations, and intra-doc links would no longer work. I suppose something is better than nothing, though?

I think so. Anyone that depends on `time` is going to run into this unless they're already in the habit of invoking `cargo doc` with `--no-deps`. Still, it's just a paper cut, but then who likes paper cuts :)

**Comment by jhpratt** [comment]
Docs can be built on stable on the master branch! It'll go out alongside the next release.
