### ISSUE TITLE
Formatting of %T

### ISSUE THREAD

**Issue by dhzavann** [time-rs/time#211]
I don't know the standard that well, but at least wikipedia claims that an ISO 8601 timestamp (%H:%M:%S) contains a zero-padded hour, which is what I also expected.

Instead it gives me %-H:%M:%S (as is also documented), but is this still valid ISO8601 as the documentation claims or is this a contradiction? It caused some slight sorting issues as we cannot sort dates formatted by %T using simple string comparison after a naive update from time 0.1. 

Meanwhile, the documentation for T in format/mod.rs says that it's "ISO 8601 time format (HH:MM:SS), equivalent to `%H:%M:%S`", which contradicts the documentation and behaviour. I haven't spent any time understanding the context of the code, so maybe it's unrelated.

I will of course just use %H:%M:%S instead in this case, this is mostly to see if this has just been overlooked.

**Comment by jhpratt** [comment]
Looks like the internal documentation is incorrect. The current behavior is correct, per the public documentation. The giant table on the index is your master guide.

Note that ISO compliance is neither guaranteed nor a goal. It _may_ be in the future, but I'm currently more focused on adding functionality than spec compliance.

**Comment by jhpratt** [comment]
Fixed on master (and therefore [time-rs.github.io](https://time-rs.github.io))
