### ISSUE TITLE
`from_unix_timestamp` overflow

### ISSUE THREAD

**Issue by rushmorem** [time-rs/time#214]
With a large or small enough timestamp, [`from_unix_timestamp` overflows](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=72af0af563b8d08b827ee01323fd4f8f). I know the documentation for `Date` says:-

> Years between -100_000 and +100_000 inclusive are guaranteed to be representable. Any values outside this range may have incidental support that can change at any time without notice.

but it's not obvious from the signature nor from the documentation of that method that it can potentially overflow.

**Comment by jhpratt** [comment]
That's a risk you take when you go outside the range that has guaranteed support. If you stay in the ±100,000 year range, the behavior will work. And as it currently stands, you could actually go well beyond the age of the universe and have it work as expected (though there's no guarantee that will continue to be the case). This would fall under the "may have incidental support" part; the implication being that it also may _not_ work.

Because this deals exclusively with data outside the supported range, I'm going to close this.

**Comment by rushmorem** [comment]
I know but considering that overflows in dates and times can have serious security consequences, IMHO it's safer to return `None` or an `Error` when one goes beyond the guaranteed times.

**Comment by jhpratt** [comment]
Sure, that's an option, but then anyone staying within the guaranteed range has to handle a case they'll never encounter. I don't want to punish people for following guarantees.

It's a guaranteed range for a reason — any values outside that _may or may not_ work. The _only_ thing I can guarantee in those situations is memory safety. If you're coding something that is taking user timestamps as input, you could certainly construct the maximum guaranteed OffsetDateTime, get the timestamp of that, and check. But that's an issue with user input verification, not time.

You'll need a _very_ strong argument to convince me I'm wrong here, as I am of the opinion that anything outside the guaranteed range is the callers responsibility to ensure correctness of.

**Comment by rushmorem** [comment]
> You'll need a very strong argument to convince me I'm wrong here

I'm not trying to convince you into doing anything nor do I think you are wrong. I certainly understand your point of view and I respect it. This crate is awesome as it is. As a user, I would be doing myself and the community at large a disservice if I saw a potential to make it even better and I kept quiet. I'm simply trying to explore this potential and see if it is something you and the community might see as desirable.

> as I am of the opinion that anything outside the guaranteed range is the callers responsibility to ensure correctness

This is true but there is no harm in going an extra step in ensuring that users use the library safely. In fact, this is something I really appreciate about Rust's ecosystem. Take `chrono`, for example. `from_timestamp` panics instead of overflowing. If one doesn't want to risk a panic, they can use `from_timestamp_opt` instead, which returns an `Option`. I'm not saying this is what we should do. In fact, I'm not a fan of panicking in libraries. Panicking has its own issues. This is just an example of one library taking that extra step.

> It's a guaranteed range for a reason — any values outside that may or may not work

This sounds like undefined behaviour and frankly it scared me a little when I read that in the `Date` documentation even though there are no memory safety issues involved. Ideally every user should read the documentation before using a library but we all know that's not always the case. I'm pretty sure not every user of the library knows about this guarantee. Especially since it's not prominently displayed in the README nor the overall documentation of the crate (https://docs.rs/time/0.2.6/time/index.html).

> Sure, that's an option, but then anyone staying within the guaranteed range has to handle a case they'll never encounter. I don't want to punish people for following guarantees.

It's not an all or nothing trade off. One way to mitigate this is to provide a `checked` variant of the method like `Duration` does for arithmetic operations.

Personally, my proposal would be to rename this method to `from_unix_timestamp_unchecked`, which clearly communicates to the user that it may or may not work for certain inputs, and then re-implement `from_unix_timestamp` to return `Result<Self, ConversionRangeError>` or something like that. If this is something you would consider, I can gladly put up a pull request. I know `_unchecked` is usually used for `unsafe` APIs but while this doesn't have any memory safety issues, the name still makes sense. The input hasn't been checked to see if it's within the guaranteed range plus an overflow here potentially has dire security consequences.

PS: To explain where I'm coming from and what motivated opening this issue in the first place, I had to check the source code to see if `from_unix_timestamp` can overflow. With the proposed API change or other such similar variation, this wouldn't be necessary.

**Comment by jhpratt** [comment]
> This is true but there is no harm in going an extra step in ensuring that users use the library safely. In fact, this is something I really appreciate about Rust's ecosystem. Take `chrono`, for example. `from_timestamp` panics instead of overflowing. If one doesn't want to risk a panic, they can use `from_timestamp_opt` instead, which returns an `Option`. I'm not saying this is what we should do. In fact, I'm not a fan of panicking in libraries. Panicking has its own issues. This is just an example of one library taking that extra step.

I considered including panicking in my previous response, but there were discussions before 0.2 was released regarding panicking methods (they're actually deprecated now).

> This sounds like undefined behaviour 

I mean, it _is_ undefined. It's as much undefined as if there were a `Time` that had the seconds set to 98. Valid memory and consistent behavior, but still undefined.

> It's not an all or nothing trade off. One way to mitigate this is to provide a `checked` variant of the method like `Duration` does for arithmetic operations.
> 
> Personally, my proposal would be to rename this method to `from_unix_timestamp_unchecked`, which clearly communicates to the user that it may or may not work for certain inputs, and then re-implement `from_unix_timestamp` to return `Result<Self, ConversionRangeError>` or something like that. If this is something you would consider, I can gladly put up a pull request. I know `_unchecked` is usually used for `unsafe` APIs but while this doesn't have any memory safety issues, the name still makes sense. The input hasn't been checked to see if it's within the guaranteed range plus an overflow here potentially has dire security consequences.

I wouldn't be opposed to having a method like `fn try_from_unix_timestamp(timestamp: i64) -> Result<Self, ComponentRangeError>`. I would have to think about the variety of use cases before making that the default though (and it would also require a major version bump). Feel free to throw together a PR if you'd like!

> PS: To explain where I'm coming from and what motivated opening this issue in the first place, I had to check the source code to see if `from_unix_timestamp` can overflow. With the proposed API change or other such similar variation, this wouldn't be necessary.

I can certainly add a note to that method specifically, since it's the only way to construct an `OffsetDateTime` aside from `.using_offset`/`.assume_offset`.
