### ISSUE TITLE
time:format::parse::ParseResult is private ? how to use it

### ISSUE THREAD

**Issue by baoyachi** [time-rs/time#222]
for this code :
```rust
fn parser_time() -> ParseResult <Time>{
        let hour = "12";
        let minute = "03";
        let second = "56";
        let format = format!("{}:{}:{}", hour, minute, second);
        let time = Time::parse(format.as_str(), "%T")?;
        time
    }
```

I just want  import `time:format::parse::ParseResult `,but find it's private ?

how can I use `ParseResult `?

**Comment by jhpratt** [comment]
The `ParseResult<T>` is just to avoid typing out `Result<T, ParseError>` in tons of places internally. There are a few options available to you:

- Use `Result<T, ParseError>`
- Define an identical alias (`type ParseResult<T> = Result<T, ParseError>`)
- Use `time::Result<T>`, which encompasses any error from the time crate.

**Comment by baoyachi** [comment]
@jhpratt tks
