### ISSUE TITLE
Doesn't build anymore for webassembly target

### ISSUE THREAD

**Issue by hce** [time-rs/time#223]
I'm using the time package as a transitive dependency. The latest build seems incompatible with webassembly. Building my project with "cargo web build" yields the following error message:

       Compiling time v0.2.7
    error[E0308]: mismatched types
       --> /home/hc/.cargo/registry/src/github.com-1ecc6299db9ec823/time-0.2.7/src/utc_offset.rs:294:53
        |
    294 | fn try_local_offset_at(datetime: OffsetDateTime) -> Option<UtcOffset> {
        |    -------------------                              ^^^^^^^^^^^^^^^^^ expected enum `std::option::Option`, found `()`
        |    |
        |    implicitly returns `()` as its body has no tail or `return` expression
        |
        = note:   expected enum `std::option::Option<utc_offset::UtcOffset>`
                found unit type `()`

**Comment by hce** [comment]
Looking a bit at the source code, I'd say this is caused by the conditional compilation statements and for webassembly, no implementation exists yet

**Comment by hce** [comment]
I'll try to fix this myself and create a pull request

**Comment by jhpratt** [comment]
Yeah, that sounds about right. I'd be fine just automatically returning `None` there for now.

**Comment by zimond** [comment]
@hce please release a new version with this fix

**Comment by jhpratt** [comment]
@zimond I will create a new release tomorrow at the earliest. Friday or Saturday is more likely — I'm finishing up exams and travelling back home.
