### ISSUE TITLE
Parsing does not support fractional seconds

### ISSUE THREAD

**Issue by aloucks** [time-rs/time#226]
Is there any plan to support parsing of fractional seconds? I checked the [formatting section](https://time-rs.github.io/time/time/index.html#formatting) but I don't see anything regarding this.

**Comment by jhpratt** [comment]
It'll be supported at some point. I'm not sure what form I want it to take, though, which is why I haven't done so yet.

**Comment by GrayJack** [comment]
Maybe implementing the GNU one first, which is `%N` for full nanoseconds as fractional second (9 digits), then moving to a way to specify less digits.

Is that a good idea?

**Comment by jhpratt** [comment]
That's certainly an option. Shouldn't be too hard to implement, either.

I'm planning on pulling my laptop back out later tonight, where I can take a look into this. A release is also likely, containing wasm support.

**Comment by jhpratt** [comment]
Live on master. I will release tomorrow.

**Comment by aloucks** [comment]
> Live on master. I will release tomorrow.

Nice!

Would you be open to a subsecond millisecond in addition to nanosecond?

**Comment by jhpratt** [comment]
Not at the current time, as there's no clear way to allow for an arbitrary number of digits. Otherwise there will just be a number of formatters that will ultimately be deprecated.

**Comment by aloucks** [comment]
What if it only accepted 3 digits ?

**Comment by jhpratt** [comment]
As I said, then there's a number of formatting specifiers that _will be_ deprecated in the future. It's better to keep the API limited until there's a way for an arbitrary number of digits (up to 9).

**Comment by jhpratt** [comment]
Released.
