### ISSUE TITLE
Add try_current_local_offset

### ISSUE THREAD

**Issue by Y0ba** [time-rs/time#227]
Currently if time library failed to get local offset it returns UTC offset. In my case I get datetime from device with local offset and converting them to `OffsetDateTime` via `PrimitiveDateTime::new(date, time).assume_offset(UtcOffset::current_local_offset())`. But if `current_local_offset` fails to get local offset my program will return wrong time. I'd like to return error in this case.

**Comment by jhpratt** [comment]
I can definitely do this — the current method is actually a wrapper around a `try_` method anyways.

**Comment by Y0ba** [comment]
`OffsetDateTime::try_now_local()` also will be useful.

**Comment by jhpratt** [comment]
Done on master!

**Comment by jhpratt** [comment]
@Y0ba FYI this has just been released in 0.2.8.
