### ISSUE TITLE
Parsing year problem

### ISSUE THREAD

**Issue by SLMT** [time-rs/time#228]
I got a problem when I parsed a string with format `%Y%m%d`. Here is a test case:

```rust
use time::Date;

fn main() {
  let date = Date::parse("20200703", "%Y%m%d");
  dbg!(date);
}
```

This prints:

```
[src/main.rs:5] date = Err(
    InvalidYear,
)
```

But, it works fine in the following case:

```rust
use time::Date;

fn main() {
  let date = Date::parse("2020 0703", "%Y %m%d");
  dbg!(date);
}
```

```
[src/main.rs:5] date = Ok(
    Date {
        year: 2020,
        ordinal: 185,
    },
)
```

It also looks like it can distinguish the month and the day when they come together, but it cannot do the same thing for the year. So, I guess this might be a bug?

**Comment by SLMT** [comment]
I look into the code of parsing years. It looks like it assumes the string of a year might have at most 6 digits so that it can handle a year greater than 9999. However, I think may be better to assume the string is 4 digits and accept a string that has more than 4 digits only when it begins with a `+`.

How do you think about this?

**Comment by jhpratt** [comment]
I've actually been aware this would likely happen, but never bothered to test it. You're 100% correct that the parser assumes can be up to six digits, as the valid years are ±100,000.

Given that the formatter inserts a `+` (per the ISO spec) when the year is more than four digits, I think parsing it the same way would make sense. It should be a relatively minor change, just adding a conditional to change the max from 6 to 4 if a `+` is parsed. I can do this at some point, likely after Tuesday (midterms for college).

**Comment by SLMT** [comment]
How about I do it later and submit a pull request?

**Comment by jhpratt** [comment]
If you'd like, sure! Just be sure to add a test case.

**Comment by SLMT** [comment]
I just submitted a pull request. Please check if it is good for you.
