### ISSUE TITLE
UtcOffset::as_duration as a public API

### ISSUE THREAD

**Issue by GrayJack** [time-rs/time#230]
I got into a problem where I need to add or sub the local offset to properly fix the time, and I only can do it using a Duration or extracting the seconds inside UtcOffset, but there is no public way to do so.

```rust
let now = if is_utc { DateTime::now() } else { DateTime::now_local() };

// inside a match slice pattern
[h1, h2, m1, m2] => {
            let hour = parse_datetime_values(&[*h1, *h2])?;
            let min = parse_datetime_values(&[*m1, *m2])?;
            let time = build_time(hour, min, now.seconds(), now.nanosecond())?;
            Ok(PrimitiveDateTime::new(now.date(), time).assume_utc().to_offset(now.offset()))
},
``` 

So, let's say that my machine is UTC -3
If I pass a string `1212`
If I do this way, when I do `to_offset()`, My hour will be `09`, but I want the final time to be 12 after I set the offset.

My solution would be adding the offset seconds to `Time` to correct this behavior.

I made this issue in a hurry, if something wasn't clear, let me know so I can explain it better :smile:

**Comment by jhpratt** [comment]
Is what you're looking for `PrimitiveDateTime::assume_offset(UtcOffset::local_offset_at(foo))`?

**Comment by GrayJack** [comment]
No, What I'm doing a lot of times is this pattern.
```
<Time> - Duration::seconds(now.offset().as_seconds().into())
```

And would be much more ergonomic if it was
```
<Time> - now.offset().as_duration()
```

**Comment by jhpratt** [comment]
Going to need some more info then, because from what you've posted it looks like you should be able to assume a specific offset and then convert it to the desired offset (which can be local).

I understand what you're asking for; I don't see why it's _necessary_. It's trivial

**Comment by GrayJack** [comment]
Yeah, I agree with you, it's easy to mix up, in my case I'm sure what I'm doing.

Ok, you have a point, maybe it's for the better to have the API so difficult to make a `Duration` for `UtcOffset` so people don't misuse it

**Comment by jhpratt** [comment]
Closing this for the reasons stated. It's already possible to do this, just a bit more verbosely. Given that it's easy to mess up, that's probably a good thing.
