### ISSUE TITLE
Can't parse / format RFC 3339 or ISO-8601 timestamps

### ISSUE THREAD

**Issue by thomcc** [time-rs/time#232]
Timestamps in https://tools.ietf.org/html/rfc3339 are really quite common.

This is pretty surprising to me (these are common) but... AFAICT these can't be specified in the format syntax because:

1. No support for fractional seconds other than full 9-digit nanoseconds (any number of fractional digits should be parsed for the standard -- but writing it it's common for things to only support 3 digits).
2. No support for timezone specified as [+-]HH:MM (only non-colon version -- but colon is required by this standard).

Even then you'd have to try multiple times

**Comment by jhpratt** [comment]
The time crate does not _currently_ purport to be RFC or ISO compliant.

As mentioned in #226, I don't have an API design for a way to support an arbitrary number of digits when parsing fractional seconds. The same is true for formatting/parsing timezone support with a colon. Once an API design is thought of and is viable, I will implement it.

I have other priorities currently, as my college schedule has been completely upended. I'm still working on the crate in my spare time, but have other (internal) improvements I'm planning on making as well. I'll get around to it at some point, though! :slightly_smiling_face:

**Comment by jhpratt** [comment]
I'm going to implement this, along with some other common formats. I should be able to provide an enum for these formats, while also allowing back-compatibility with the current method (accepting both string types).

**Comment by jhpratt** [comment]
Support for formatting as RFC3339 is now on master. To use it, you'd want to do something along the lines of `OffsetDateTime::now_local().format(time::Format::Rfc3339)`. Parsing is next up :)

I would have liked to have used typestate, but unfortunately there are compiler limitations that prevent its usage alongside overloading the function.

**Comment by jhpratt** [comment]
Support for parsing on master. I believe I am fully spec compliant, with the exception of formatting years with more than four digits. Parsing should be fully compliant.
