### ISSUE TITLE
Reverse dependency upgrades to 0.2

### ISSUE THREAD

**Issue by jhpratt** [time-rs/time#235]
This is a tracking issue for the effort to upgrade a number of reverse dependencies to time 0.2. If you're a maintainer or contributor to a crate and looking to upgrade from time 0.1 to 0.2, leave any questions you may have below! I'll do my best to address your questions & concerns.

Crates that have already updated:

- cookie [[ref](https://github.com/SergioBenitez/cookie-rs/pull/134)]
- rocket [[ref](https://github.com/SergioBenitez/Rocket/commit/7c1b8dc9adbeea0a33d72b5be339f6e98c03d62b)]
- actix [[ref](https://github.com/actix/actix-web/pull/1372)]
- rust-postgres [[ref](https://github.com/sfackler/rust-postgres/commit/2082d4f781a211f4248cbff026716b5f63bba04a)]
- rusoto [[ref](https://github.com/rusoto/rusoto/commit/bb691ce3baa05e59c0d4487a47fa5826afa4614a)]

Crates with open PRs:

- hyper [[ref](https://github.com/hyperium/hyper/pull/2139)]
- bson-rust [[ref](https://github.com/mongodb/bson-rust/pull/139)] — removal

Other crates that could be updated:

- reqwest (blocked by hyper)
- rustc-test — may not need the time crate at all
- rusqlite
- instant
- diesel
- nickel
- pbr
- rouille

**Comment by g2p** [comment]
chrono should be updated as well.

**Comment by jhpratt** [comment]
@g2p iirc this was brought up on the chrono repository and they didn't express much desire to upgrade.

**Comment by stlankes** [comment]
I want to write some examples for [RustyHermit](https://github.com/hermitcore/rusty-hermit). However, crates like hyper depends on time 0.1.x, which doesn't support the target `hermit`. Is it possible to add support for the target `hermit` in time 0.1.x? Or do you think they want to support time 0.2 soon?

**Comment by jhpratt** [comment]
Time 0.1 likely won't be getting support for anything else, as there is a newer version (and a 0.3 in the works).

As you've noted, hyper depends on time 0.1. There's an open PR to upgrade to 0.2, as indicated in the issue.
