### ISSUE TITLE
Get cannot find function `precise_time_ns` in crate `time` when using ::time::precise_time_ns()

### ISSUE THREAD

**Issue by jl-a** [time-rs/time#237]
I don't use `time` directly, but it is a dependency of a crate that I use. I ran `cargo update` and `time` was updated from 0.2.6 to 0.2.9, after which the dependency failed to build, throwing the error

```
error[E0425]: cannot find function `precise_time_ns` in crate `time`
   --> offline_crates/imageflow/26135e6/imageflow_helpers/src/licensing/mod.rs:187:29
    |
187 |         let start = ::time::precise_time_ns();
    |                             ^^^^^^^^^^^^^^^ not found in `time`
```
(and the same error everywhere else `time::precise_time_ns()` was used.

I manually reverted `time` to 0.2.6 in `Cargo.lock` and the dependency built fine. Going through `time`'s commits I noticed that https://github.com/time-rs/time/commit/9665008525d27aebb07b26d51eeb31192b5f6b05 released in 0.2.8 was an update related to parsing and formatting nanoseconds, so suspect a bug of some sort was introduced then.

**Comment by jhpratt** [comment]
It looks like this error is coming from the imageflow_helpers crate? That would be an issue over there, as the function [very much still exists](https://github.com/time-rs/time/blob/master/src/lib.rs#L546-L564). However, a quick search shows they are using glob version dependencies, so any breaking changes would be pulled in my default when they're made in the appropriate version bump.

If you can provide more info, I'll be happy to try to reproduce this locally to give a more definite answer.
