### ISSUE TITLE
0.2.7 includes a semver breaking change

### ISSUE THREAD

**Issue by SergioBenitez** [time-rs/time#239]
0.2.7 includes commit https://github.com/time-rs/time/commit/a93d32efffba2f96512fe3758d56cb3ac037fe82, which is a (silent) semver breaking change. This is causing `cookie-rs` to [fail to test](https://github.com/SergioBenitez/cookie-rs/runs/534871606). I also don't see this panicking behavior documented anywhere.

This is at least the third semver breaking change without a semver version bump this library has experienced since moving to `0.2`, not to mention the [failure to build](https://github.com/SergioBenitez/Rocket/issues/1258) in `0.2.8`. This makes using the library a hazard. My advice is to consider asking for external review before releasing a new version. At present, I am considering a migration away from the library.

**Comment by jhpratt** [comment]
Without seeing the backtrace I can't be positive, but given the error I believe this actually has nothing to do with the overflow checks in `Duration`. Rather, it is a result of the [clearly-stated](https://docs.rs/time/0.2.9/time/struct.Date.html) validity guarantee that has been present since the initial 0.2.0 release:

> Years between -100_000 and +100_000 inclusive are guaranteed to be representable. Any values outside this range may have incidental support that can change at any time without notice. If you need support outside this range, please file an issue with your use case.

With regard to 0.2.8 _possibly_ not building, I presume you've seen #233. As is standard practice, I allowed the usage of any semver version back to the most recent major (0.1). I naïvely assumed this would work; this was obviously not the case. I have since verified all other direct dependencies work at both the minimum and current version in the semver range.

---

Are there any tools that would allow me to perform something along the lines of a crater run? If I could manually give something a list of libraries (starting with all reverse dependencies) and ensure that there are no regressions, that would be ideal.

External review is far from perfect — we don't need to look any further than the standard library where breaking changes have been introduced (without an FCP) on the _unverified assumption_ that it wouldn't break anything. This is precisely what occurred with overflow checks on `Duration` arithmetic. I could not conceive of a single use case where one would actively want a `Duration` to overflow, given it is capable of storing lengths of time vastly longer than the age of the universe, and it does not appear that this is the cause of the CI failure in the cookie crate.

**Comment by SergioBenitez** [comment]
> Without seeing the backtrace I can't be positive, but given the error I believe this actually has nothing to do with the overflow checks in `Duration`. Rather, it is a result of the [clearly-stated](https://docs.rs/time/0.2.9/time/struct.Date.html) validity guarantee that has been present since the initial 0.2.0 release:

The error is:

> thread 'tests::format' panicked at 'year must be in the range -100000..=100000 (was 219250468)', <::std::macros::panic macros>:5:6

Looking at the test, it's obvious this comes from `Duration`. But, here are the relevant lines in the backtrace:

> 14: time:: date::Date::from_julian_day
             at ./<::std::macros::panic macros>:5
15: <time:: date::Date as core::ops::arith::Add<time::duration::Duration>>::add
             at .cargo/registry/src/github.com-1ecc6299db9ec823/time-0.2.9/src/date.rs:1027
  16: <time::primitive_date_time::PrimitiveDateTime as core::ops::arith::Add<time::duration::Duration>>::add
             at .cargo/registry/src/github.com-1ecc6299db9ec823/time-0.2.9/src/primitive_date_time.rs:549
  17: <time::offset_date_time::OffsetDateTime as core::ops::arith::Add<time::duration::Duration>>::add
             at .cargo/registry/src/github.com-1ecc6299db9ec823/time-0.2.9/src/offset_date_time.rs:768


> Are there any tools that would allow me to perform something along the lines of a crater run? If I could manually give something a list of libraries (starting with all reverse dependencies) and ensure that there are no regressions, that would be ideal.

Besides [crater itself](https://github.com/rust-lang/crater), not that I know of, but writing such a script yourself wouldn't be too difficult, for instance using `cargo-edit-locally`. 

> External review is far from perfect — we don't need to look any further than the standard library where breaking changes have been introduced (without an FCP) on the _unverified assumption_ that it wouldn't break anything. This is precisely what occurred with overflow checks on `Duration` arithmetic.

Changes to the standard library don't make it to stable for ~12 weeks after they're introduced, allowing time for catching bugs. What's more, one can easily roll back to an older version. Changes to this library affect all of its dependencies immediately, and rolling back a transitive dependency can be difficult.

>  I could not conceive of a single use case where one would actively want a `Duration` to overflow, given it is capable of storing lengths of time vastly longer than the age of the universe, and it does not appear that this is the cause of the CI failure in the cookie crate.

Unfortunately it doesn't matter if it's reasonable behavior or not. What matters is what's specified. In this case, even now, it's not specified that `year` needs to be within a given range, neither in `Duration` nor `OffsetDateTime` nor `PrimitiveDateTime`. As it stands, it is impossible to know, aside from reading the code or running into this issue inadvertently, that a panic can happen under any `Add` operation. What's more, I'd argue that this is incredibly odd behavior for a `time` library: nothing should ever panic; _something_ reasonable should always happen. For instance, if you _must_ cap the year (why do you need to?), then simply bound the year or wrap around. But panicking is incredibly odd.

**Comment by jhpratt** [comment]
> The error is:
> 
> > thread 'tests::format' panicked at 'year must be in the range -100000..=100000 (was 219250468)', <::std::macros::panic macros>:5:6
> 
> Looking at the test, it's obvious this comes from `Duration`. But, here are the relevant lines in the backtrace:
> 
> > 14: time:: date::Date::from_julian_day
> > at ./<::std::macros::panic macros>:5
> > 15: <time:: date::Date as core::ops::arith::Addtime::duration::Duration>::add
> > at .cargo/registry/src/github.com-1ecc6299db9ec823/time-0.2.9/src/date.rs:1027
> > 16: <time::primitive_date_time::PrimitiveDateTime as core::ops::arith::Addtime::duration::Duration>::add
> > at .cargo/registry/src/github.com-1ecc6299db9ec823/time-0.2.9/src/primitive_date_time.rs:549
> > 17: <time::offset_date_time::OffsetDateTime as core::ops::arith::Addtime::duration::Duration>::add
> > at .cargo/registry/src/github.com-1ecc6299db9ec823/time-0.2.9/src/offset_date_time.rs:768

As I suspected, it does originate from `Date` (see line 14). A `Duration` has no concept of a "year", let alone with a fixed epoch. What is happening is you're adding a `Duration` to a `PrimitiveDateTime` (and therefore `Date`), causing the year to go out of the valid range.

> Besides [crater itself](https://github.com/rust-lang/crater), not that I know of, but writing such a script yourself wouldn't be too difficult, for instance using `cargo-edit-locally`.

Thanks, I wasn't aware of that crate. I'm definitely going to take a look into this, along with possible integration into CI. If I can get it to work with GitHub Actions, I should be able to trigger it via a variety of methods.

> Changes to the standard library don't make it to stable for ~12 weeks after they're introduced, allowing time for catching bugs. What's more, one can easily roll back to an older version. Changes to this library affect all of its dependencies immediately, and rolling back a transitive dependency can be difficult.

Ironically, this still isn't perfect. There have been plenty of stable-to-stable regressions. But that's not the point here, so there's no purpose in continuing. If I can get an automated crater-like system for time, it should catch a variety of real-world use cases.

> What's more, I'd argue that this is incredibly odd behavior for a `time` library: nothing should ever panic; _something_ reasonable should always happen. For instance, if you _must_ cap the year (why do you need to?), then simply bound the year or wrap around. But panicking is incredibly odd.

It is my intent to saturate `Date`s in 0.3. `Time`s already wrap. `UtcOffset` methods will return a `Result`, as macros now provide the capability for values known at compile-time.

The reasoning for capping the year was to allow for the possibility of restructuring internally, namely bitpacked fields. I still haven't ruled it out, but I'd want to do some performance checks first.
