### ISSUE TITLE
Add ISO8601 +-HH:MM to formatting

### ISSUE THREAD

**Issue by Firstyear** [time-rs/time#241]
There are a large number of format strings supported by time (ie https://docs.rs/time/0.2.9/time/index.html#formatting ). `%z` outputs or parses a UTC offset with "[+-]HHMM". However in ISO8601 it is also valid to have "[+-]HH:MM", and in expected fashion, some other libraries only accept the ":" seperated format. It would be good if time could also output and parse this. Thanks!

**Comment by jhpratt** [comment]
See #236; there are planned improvements to the formatter & parser. Also note that there is actually support for RFC3339/ISO8601 formatting & parsing on master. I will likely create a 0.2.10 release with this functionality soon.

Do you need support for formatting & parsing with the colon on its own, or is RFC/ISO support sufficient for your use case?

**Comment by Firstyear** [comment]
I think the ISO support is enough for my use case, thanks for the quick response and really appreciate your time (pun intended :) )

**Comment by jhpratt** [comment]
Closing this as your use case is already covered on master :slightly_smiling_face:

**Comment by Weasy666** [comment]
@jhpratt So...i need to ask a kinda dumb question...how can i parse ISO8601 with time 0.2.22? 😅
`time::OffsetDateTime::parse("2039-01-01T00:00:00+00:00", "%FT%T%z").unwrap()` throws an error

**Comment by jhpratt** [comment]
@Weasy666 As indicated in documentation, `%z` does not have a colon present. Instead of passing a `%FT%T%z` as the format description, you can pass `time::Format::Rfc3339`. This is compatible with ISO8601 (I'm fairly certain).

Probably wouldn't be a bad idea to add a doc alias for "ISO8601", which would let it show up in search results.

**Comment by Weasy666** [comment]
Ah...nice! Thanks for the quick reply. `Rfc3339` works! Doc alias sounds like a good idea!

**Comment by jhpratt** [comment]
It's set to stabilize this coming Thursday! I don't like the `#[cfg_attr]` hack for `doc_cfg` that I use now, so I'd rather just wait a few days haha

**Comment by Weasy666** [comment]
Other people can search the issues and can see the solution here, so no hurry. I guess. 😀
