### ISSUE TITLE
support #![no_std] targets without global allocation

### ISSUE THREAD

**Issue by berkowski** [time-rs/time#249]
#246 gets `time` building on `#![no_std]` but the crate still requires the presence of a global allocator for use.  For example, on a bare-metal thumbv6m target compiled with `--no-default-features` one gets:
```
error: no global memory allocator found but one is required; link to std or add `#[global_allocator]` to a static item that implements the GlobalAlloc trait.

error: `#[alloc_error_handler]` function required, but not found

error: aborting due to 2 previous errors
```
This appears to be mostly due to a few `Box<T>`'s and `Vec<T>`'s used in parsing and error handling.

I've been able to `time` running on my target by taking the heavy-handed approach of pushing offending portions of code behind a new `alloc` feature.  I lose

- String parsing
- `Display` implementations
- The helper `time!` and `date!` macros (I think)

A nice surprise is that `serde` support still works!

To me that's well worth the trade-off of having a library that can do calendar math on an embedded platform.  I can do what limited string parsing I need with something like `nom` and use other constructors here.

It would be great if `time` supported this out of the box but I'm not sure how you would want to go about such an invasive change.  I'd be happy to start a PR if there's interest.

**Comment by jhpratt** [comment]
A couple things:

- `Box<T>` is only used in one or two locations, and for the sole purpose of reducing the size of an enum/struct on the stack. This could be changed, but I'm not sure it's worth it. Benchmarks might be necessary.
- `Vec<T>` is used for two purposes:
  - Error _reporting_ — it's used to store what the minimum and/or maximum values are predicated on for a `ComponentRangeError`. I _might_ be able to use a slice reference combined with a lifetime, but the borrow checker might not agree. There's likely some other hacky ways around it as well.
  - Parsing of the formatting strings. I don't think there's any way around this, as none of this is statically knowable.

Note that _fixed_ formats like RFC3339 (present as of 0.2.10) don't run into the issue with parsing formatting strings. Those could theoretically be supported even in no-alloc environments.

The macros shouldn't cause any issue, as those are done fully at compile-time and emit what is essentially an unchecked constructor.

---

I'm actually interested in switching to nom for parsing entirely. The main issue here is compatibility with custom errors, which _should_ have documentation by the time nom 6 is released. This shouldn't have any effects on public APIs, though.

This is something I'd be interested in, but adding a feature flag is a breaking change, so this couldn't happen until 0.3. You're more than welcome to try to figure things out, but I'll caution you that this is all _very_ tentative. There's still a lot to be figured out, and 0.3 is a ways off (I'm quite busy currently).

**Comment by berkowski** [comment]
I'll go ahead and start a PR now with what I have.  It's probably not even an adequate starting point but.. it's something, and at least in the short term might be useful to a few others.

I'm not too concerned about the pace of adoption.  It'll be great to have it merged eventually but for now I'm OK maintaining my own fork for my needs while the work continues.

**Comment by jhpratt** [comment]
For those coming here from TWIR, I thought this issue would be a good one to tackle for Hacktoberfest!

My current thought is to eliminate the boxing that happens in error handling, placing anything that relies on allocation behind an `alloc` feature flag. This flag would be implicitly enabled by the `std` feature. Don't worry about formatting at all. It's going to be redone almost entirely from scratch, so any effort here would be nearly worthless.

Note that any PR doing this should be based on the v0.3 branch, not main. Unlike at the time of my previous comment, v0.3 is relatively stable with the exception of formatting.

**Comment by garasubo** [comment]
I'm intersted in no_std programming in Rust. Could you assign this issue to me?

**Comment by jhpratt** [comment]
Done! Let me know if you need anything.
