### ISSUE TITLE
Optional WASM support

### ISSUE THREAD

**Issue by frondeus** [time-rs/time#254]
Hello, my company is using `time` for classic web service application.
It is a great piece of software, however, we noticed that in Cargo.lock there are some dependencies that are unused and only slow down our CI pipeline:

```rust
- stdweb v0.4.20
- stdweb-derive v0.5.3
- stdweb-internal-macros v0.2.9
- stdweb-internal-runtime v0.1.5
- wasi v0.9.0+wasi-snapshot-preview1
- wasm-bindgen v0.2.62
- wasm-bindgen-backend v0.2.62
- wasm-bindgen-macro v0.2.62
- wasm-bindgen-macro-support v0.2.62
- wasm-bindgen-shared v0.2.62
```

While we are glad that `time` supports `WASM` we wish it could be an optional feature instead of being default dependency.

Is this even feasible? I can imagine this would be breaking change for all WASM users.

**Comment by jhpratt** [comment]
Check out the v0.3 branch. I recently gated support for obtaining the local offset, which is the only location stdweb is used.

If this isn't sufficient, please provide some more details about your use case.
