### ISSUE TITLE
Serde OffsetDateTime as Unix timestamp

### ISSUE THREAD

**Issue by mwkroening** [time-rs/time#255]
I need to de/serialize `OffsetDateTime` from/to Unix timestamps.

For that purpose I wrote a module for use in combination with [serde's with-annotation](https://serde.rs/field-attrs.html#with).
Would such a module be in scope for this project? If yes, I would happily create a PR.

**Comment by jhpratt** [comment]
As I'm sure you can imagine, different people have different needs for serialization. With time v0.2, a round-trip ser/de actually loses information, as the `UtcOffset` isn't encoded. This would also be the case with using Unix timestamps. The v0.3 branch has changed ser/de to use the defaults, essentially, which doesn't lose any information.

My recommendation would be to have a wrapper struct, which would allow you to implement `Serialize` and `Deserialize` as you need. Assuming you implement [`Deref`](https://doc.rust-lang.org/stable/std/ops/trait.Deref.html), it would also be mostly transparent. You'd also only need to use this when necessary, and could fall back to an `OffsetDateTime` for nearly all purposes.

**Comment by mwkroening** [comment]
Thanks for the fast response!

I just wanted to know if this clearly alternative approach to de/serialization would be useful for addition to this project. I did not intend to replace the default. Modules fulfilling the requirements of serde's with-annotation actually allow overriding the `Serialize` and `Deserialize` implementations per field without having to resort to a wrapper struct.

I am completely fine with this being out of scope of this project though.

**Comment by jhpratt** [comment]
I wasn't aware serde allowed for end-users to "override" the default, so to speak.

I'd be open to a pull request for the Unix timestamp on `OffsetDatetime` specifically, given it's probably one of the more common use cases. This can be based on master and not v0.3, as it would be safe to add as non-default.
