### ISSUE TITLE
Unexpected behavior around OffsetDateTime serialization/deserialization

### ISSUE THREAD

**Issue by djahandarie** [time-rs/time#257]
I send a serialized `OffsetDateTime` (with a non-UTC timezone) over a websocket and deserialize it on the other end, and it ends up as a UTC `OffsetDateTime`.

It seems like the code here https://docs.rs/time/0.2.15/src/time/offset_date_time.rs.html#35 is intentionally doing this, but it was quite unexpected for me (since I would have just sent a `PrimitiveDateTime` or `DateTime` as UTC if that's what I wanted), and it is causing me to need to send an extra `UtcOffset` out-of-bound and manually readjust all my timezones on the receiving end.

**Comment by djahandarie** [comment]
Err, after reading other issues more closely I see you mention this in this comment from earlier today... https://github.com/time-rs/time/issues/255#issuecomment-624887602

Not sure what to do with this issue, please close it if you feel that this is already sufficiently tracked (or fixed somewhere)!

**Comment by jhpratt** [comment]
Yeah, this was a bad decision early on. Unfortunately fixing it creates back-compatability issues. It's already fixed on the 0.3 branch, though! More internal details are stable so it's not serialized as a timestamp at all (essentially using the default, passing fields and the struct name).
