### ISSUE TITLE
[Feature] Convert between OffsetDateTime and i64 where the i64 is nanoseconds since the UNIX epoch

### ISSUE THREAD

**Issue by mehcode** [time-rs/time#259]
I have several projects in a space where I need nanosecond precision timestamps. I store these in PostgreSQL as `INT8` (`i64`) which gives ~500 -ish years which is more than enough for my domain.

Chrono has an interesting anecdote on this:

https://docs.rs/chrono/0.4.11/chrono/struct.DateTime.html#method.timestamp_nanos

> Note that this does reduce the number of years that can be represented from ~584 Billion to ~584. (If this is a problem, please file an issue to let me know what domain needs nanosecond precision over millennia, I'm curious.)

**Proposal**

```rust
// UNIX nanoseconds -> OffsetDateTime
OffsetDateTime::from_unix_timestamp_nanos(nanos)
```

Similar to https://docs.rs/time/0.2.16/time/struct.OffsetDateTime.html#method.from_unix_timestamp

```rust
// OffsetDateTime -> UNIX nanoseconds
dt.timestamp_nanos()
```

Similar to https://docs.rs/time/0.2.16/time/struct.OffsetDateTime.html#method.timestamp

Side note, should this method be called `.unix_timestamp_nanos()` ? It feels inconsistent with the `from_` version.

**Comment by jhpratt** [comment]
This wouldn't be too difficult to implement. I'd likely end up using an i128, though, as it would provide functionality across the full range of valid dates (±100,000 years in 0.2, ±999,999 years in 0.3).

**Comment by jhpratt** [comment]
Finally getting around to doing this. You're absolutely right that the method should be called `.unix_timestamp_nanos()` and `.unix_timestamp()` for consistency. I'll make this change in 0.3.
