### ISSUE TITLE
[Feature] Construct an OffsetDateTime from a normal UNIX timestamp (in seconds) and the fractional nanoseconds

### ISSUE THREAD

**Issue by mehcode** [time-rs/time#260]
Equivalent method in chrono:

https://docs.rs/chrono/0.4.11/chrono/naive/struct.NaiveDateTime.html#method.from_timestamp

As we already have a `.from_unix_timestamp` that only takes seconds, could/should we make a breaking change in v0.3 or perhaps another method?

---

Related to #259 and my need to deal in nanosecond timestamps but sometimes I have the 12-byte pair.

**Comment by jhpratt** [comment]
What's the use case for this that #259 wouldn't cover?

**Comment by mehcode** [comment]
```rust
OffsetDateTime::from_unix_timestamp(secs, nanos)
```

```rust
OffsetDateTime::from_unix_timestamp_nanos(
    (secs as i128 * 1_000_000_000) + (nanos as i128))
```

The latter feels a lot more messy. I've seen it here:
 
 - https://golang.org/pkg/time/#Unix
 - https://docs.rs/chrono/0.4.11/chrono/naive/struct.NaiveDateTime.html#method.from_timestamp

Another idea for this use case is I could write (after reading through the docs):

```rust
OffsetDateTime::from_unix_timestamp(s) + ns.nanoseconds()
```

Yeah.. writing that out this version looks fine to me. Perhaps a mention in the docs for `from_unix_timestamp` as I was coming from chrono and its `from_timestamp`.

**Comment by jhpratt** [comment]
I think `OffsetDateTime::from_unix_timestamp(s) + ns.nanoseconds()` is quite clear already, as you've stated. Changing the label here to docs, where it can get a brief mention.
