### ISSUE TITLE
[Feature] Parse fractional nanoseconds of various widths

### ISSUE THREAD

**Issue by mehcode** [time-rs/time#261]
I (unfortunately) have a **large** amount of textual timestamps that look like the following. The key issue is a variable (3, 6, or 9) digits after the point. I believe Java formats timestamps like this by default.

```
2020-05-12T23_41_10.061774001Z
2020-05-12T23_40_45.010569Z
2020-05-12T23_40_40.321Z
```

I can't figure out how to parse that with the format codes for `time`.

In chrono, the format code is:

```%Y-%m-%dT%H_%M_%S%.fZ```

**Comment by jhpratt** [comment]
This is planned as part of #236.

Right now, it's too tedious to support nine different modifiers, especially because it's specific to the nanoseconds specifier. With the various changes I'm planning, there will be completely separate specifiers for each modifier, rather than storing it alongside.

**Comment by mehcode** [comment]
:+1: Left some thoughts there. Thanks for the great work you've done on reviving this library.
