### ISSUE TITLE
Compilation failure on nightly 1.45.0 2020-05-24

### ISSUE THREAD

**Issue by timvisee** [time-rs/time#262]
I just started seeing a compilation error in `time-macros-impl` `v0.1.1` when using the latest Rust nightly, which I'm using in [ffsend-api](https://github.com/timvisee/ffsend-api).

This may just be a temporary nightly regression, I'm not sure. I figured it'll be useful to track this here anyway.

Here's the Rust version that was used:

```
rustc 1.45.0-nightly (46e85b432 2020-05-24)
cargo 1.45.0-nightly (500b2bd01 2020-05-18)
```

Here is the error that comes up:

```
 error: expected identifier
  --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/time-macros-impl-0.1.1/src/lib.rs:84:20
   |
84 |               pub fn $name(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
   |                      ^^^^^
...
91 | / impl_macros! {
92 | |     time: Time,
93 | |     offset: Offset,
94 | |     date: Date,
95 | | }
   | |_- in this macro invocation
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
error: aborting due to previous error
error: could not compile `time-macros-impl`.
```

See the error on the bottom of this CI log here: 
https://gitlab.com/timvisee/ffsend-api/-/jobs/566079187#L735

**Comment by jhpratt** [comment]
I'll look into this when I'm on my laptop, but aftet quick look at the source code there, I see absolutely nothing wrong with how I've implemented that macro.

If this is in fact a regression that isn't on me, I'll file an issue on rust-land/rust pointing to this.

**Comment by timvisee** [comment]
It appears someone already opened an issue for it a day ago: https://github.com/rust-lang/rust/issues/72545

**Comment by jhpratt** [comment]
Looking at that issue, it appears as though it was an issue with proc macro hack, which has been fixed.

I believe the solution to this is to run `cargo update`, which will pull in the appropriate version of proc macro hack. If that doesn't work, let me know, and I'll see if publishing a new version myself helps.

**Comment by xStrom** [comment]
`cargo update -p proc-macro-hack` fixes the issue, no need for a new release.

**Comment by jhpratt** [comment]
Thanks for confirmation @xStrom! In that case, I'll just close this issue, leaving it as a signpost for anyone running into this.
