### ISSUE TITLE
Format should use Cow for Custom

### ISSUE THREAD

**Issue by CryZe** [time-rs/time#266]
More often than not is the custom format a &'static str (or maybe &'a str) rather than a String. Heap allocating there is unnecessary.

**Comment by jhpratt** [comment]
This is a breaking change due to the addition of a lifetime. As such, it can't take place in 0.2. I've already made the switch to `Cow` on the v0.3 branchv— I might end up switching entirely to `&str` because we never actually need to modify the string.
