### ISSUE TITLE
time from crates.io doesn't support no_std

### ISSUE THREAD

**Issue by mattico** [time-rs/time#280]
https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#multiple-locations

> It is possible to specify both a registry version and a git or path location. The git or path dependency will be used locally (in which case the version is ignored), and when published to a registry like crates.io, it will use the registry version.

https://github.com/time-rs/time/blob/ad4740f36895130e33fcf8eddee54cc91ef4a57c/Cargo.toml#L32

So, while CI uses the path dependency, the crates.io crate uses the old `time-macros` from 8 months ago, which does not support no_std.

**Comment by jhpratt** [comment]
What version of `time-macros-impl` is in your `Cargo.lock` file? Performing `cargo update` should suffice, I believe.

**Comment by mattico** [comment]
The problem occurs while compiling `time-macros`.  `time-macros` 0.1.0, the most recent version on crates.io does not include https://github.com/time-rs/time/commit/a933f2ace97829c9515a012878a6bf21bf114d22.

```
   Compiling time-macros v0.1.0
error[E0463]: can't find crate for `std`
  |
  = note: the `thumbv7em-none-eabihf` target may not be installed

error: aborting due to previous error
```

```toml
[[package]]
name = "time"
version = "0.2.22"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "55b7151c9065e80917fbf285d9a5d1432f60db41d170ccafc749a136b41a93af"
dependencies = [
 "const_fn",
 "standback",
 "time-macros",
 "version_check",
]

[[package]]
name = "time-macros"
version = "0.1.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "9ae9b6e9f095bc105e183e3cd493d72579be3181ad4004fceb01adbe9eecab2d"
dependencies = [
 "proc-macro-hack",
 "time-macros-impl",
]

[[package]]
name = "time-macros-impl"
version = "0.1.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "e5c3be1edfad6027c69f5491cf4cb310d1a71ecd6af742788c6ff8bced86b8fa"
dependencies = [
 "proc-macro-hack",
 "proc-macro2",
 "quote",
 "standback",
 "syn",
]
```

**Comment by jhpratt** [comment]
Have you tried performing `cargo update` as suggested? I'm pretty sure this updates indirect dependencies as well.

**Comment by mattico** [comment]
Yes, I have run `cargo update`. I am using the most recent version of time-macros from crates.io. The most recent version is 0.1.0. That version does not include this line:

https://github.com/time-rs/time/commit/a933f2ace97829c9515a012878a6bf21bf114d22#diff-d5f397db43b8797da48f8cb404ede974R1

which is required to build on no_std.

**Comment by jhpratt** [comment]
Confirmed. Not sure how I missed this before. I'll get a new `time-macros` release out today that includes everything already on main. Once that's out, `cargo update` will suffice.

**Comment by mattico** [comment]
Thanks so much!

**Comment by jhpratt** [comment]
I've just pushed and published the relevant commit. Let me know if `cargo update` doesn't work for whatever reason 🙂
