### ISSUE TITLE
[Feature] Provide Arbitrary trait implementation(s)?

### ISSUE THREAD

**Issue by emlun** [time-rs/time#286]
I've found [`quickcheck`](https://crates.io/crates/quickcheck) to be a quite useful way to write tests. How about providing `Arbitrary` implementations for the types in this library as an optional feature? I'll volunteer to do it. :slightly_smiling_face:

I'm not completely familiar with the Rust ecosystem on this matter, though (I've mostly done the similar thing in Scala) - it looks like there's both `quickcheck`'s own `quickcheck::arbitrary::Arbitrary` trait, and a different `arbitrary::Arbitrary` trait in the [`arbitrary`](https://crates.io/crates/arbitrary) crate, with no apparent relation between the two. I'm not sure which would be better to implement (if not both) - the quickcheck one seems necessary for quickcheck itself, but [`libfuzzer`](https://github.com/rust-fuzz/libfuzzer) uses the one from the `arbitrary` crate. I'm leaning towards starting with the quickcheck one since that enables more fine-grained tests than fuzzing for full-on crashes.

**Comment by jhpratt** [comment]
While I'm aware of quickcheck, I'm not familiar with exactly how it's used. How would implementing the `Arbitrary` trait (behind a flag, of course) be useful to an end user?

**Comment by emlun** [comment]
Implementing `quickcheck::Arbitrary` would allow users to write tests like this:

```rust
use time::Date;
use quickcheck::quickcheck;

struct DateRange {
    from: Date,
    to: Date,
}

impl DateRange {
    fn new(from: Date, to: Date) -> Result<Self, ()> {
        Ok(DateRange { from, to })
    }
}

quickcheck! {
    fn date_range_is_well_defined(from: Date, to: Date) -> bool {
        let r = DateRange::new(from, to);
        if from <= to {
            r.is_ok()
        } else {
            r.is_err()
        }
    }
}
```

Without it you get a trait bound error:

```
error[E0277]: the trait bound `time::date::Date: quickcheck::arbitrary::Arbitrary` is not satisfied
15  | / quickcheck! {
16  | |     fn date_range_is_well_defined(from: Date, to: Date) -> bool {
17  | |         let r = DateRange::new(from, to);
18  | |         if from <= to {
...   |
23  | |     }
24  | | }
    | |_^ the trait `quickcheck::arbitrary::Arbitrary` is not implemented for `time::date::Date`
```

and you'd have to work around it by either constructing the `Date`s from smaller components, or adding some wrapper around `Date` so you can implement `Arbitrary` for the wrapper type (because you can't add implementations for imported traits to imported types).

**Comment by jhpratt** [comment]
Gotcha. Feel free to put together a PR. I imagine you'll be able to use code similar to that for the rand impls. This should be placed behind a feature flag (`quickcheck` will suffice).

With regard to checking this in CI, right now it checks the full powerset of feature flags. Given the increasing number of flags, this is becoming a bit much, so I'll have to think about a better way to handle this while still ensuring all combinations work.
