### ISSUE TITLE
Can't compile time v0.2.23 with rust 1.48.0 on MacOS

### ISSUE THREAD

**Issue by ffactory-ofcl** [time-rs/time#295]
Hi, I've gone through the cargo.toml of my project to update some dependencies and am now getting the following error:
```
error[E0624]: associated function `to_mmp` is private
  --> /Users/ffactory/.cargo/registry/src/github.com-1ecc6299db9ec823/time-0.2.23/build.rs:30:69
   |
30 |         Some((version, channel, _)) if channel.is_dev() => (version.to_mmp().1 - 2, channel),
   |                                                                     ^^^^^^ private associated function

error[E0624]: associated function `to_mmp` is private
  --> /Users/ffactory/.cargo/registry/src/github.com-1ecc6299db9ec823/time-0.2.23/build.rs:31:73
   |
31 |         Some((version, channel, _)) if channel.is_nightly() => (version.to_mmp().1 - 1, channel),
   |                                                                         ^^^^^^ private associated function

error[E0624]: associated function `to_mmp` is private
  --> /Users/ffactory/.cargo/registry/src/github.com-1ecc6299db9ec823/time-0.2.23/build.rs:32:49
   |
32 |         Some((version, channel, _)) => (version.to_mmp().1, channel),
   |                                                 ^^^^^^ private associated function
```

Is that a known bug? I couldn't find anything online, so I'm asking here.

My version: `stable-x86_64-apple-darwin - rustc 1.48.0` and MacOS 11.0.1

<details>
<summary>This is my Cargo.toml:</summary>

```
actix-rt = "1.1"
actix = "0.9"
actix-web = {version = "3.2", features = ["rustls"] }
actix-web-actors = "3.0"
actix-files = "0.4"
actix-service = "1.0"
actix-cors = "0.5"
tokio = "0.3"

base64 = "0.13"
async-std = "1.7"
serde = "*"
serde_json = "*"
csv = "1.1"
rustls = "0.19"
env_logger = "0.8"
rand = "0.7"
futures = "0.3"
sha3 = "0.9"
```
</details>

**Comment by jhpratt** [comment]
Have you tried just running `cargo update`? That function used to be private before I created a PR a while back making it (and similar methods) public.

**Comment by ffactory-ofcl** [comment]
That worked 🤦‍♂️  god, why didn't I think of that. Thanks so much for the quick help :)

**Comment by jhpratt** [comment]
No problem! You caught me at the perfect time — I was just working on some code and was just finishing up for the night.

I was also looking into issue templates, which would _hopefully_ help people out so filing an issue isn't necessary. Maybe tomorrow!

**Comment by ffactory-ofcl** [comment]
Fewer issues are of course better but I think the problem I had is not time-specific at all, more of a rust-problem. Cargo should probably suggest running `cargo update` when a build fails on library-code, dependencies were changed or the local version is out of date. Good night though.

**Comment by dvdplm** [comment]
> That function used to be private before I created a PR a while back making it (and similar methods) public.

Is this in a released version somewhere? I have `time = "0.2"` in my Cargo.toml and it picks up v0.2.23 which fails as reported here (`rustc 1.49.0-nightly (a9cd294cf 2020-10-22)` on macos).

**Comment by ffactory-ofcl** [comment]
Had 2.2.23 somewhere in my cargo tree as well but after `cargo update` everything worked.

**Comment by jhpratt** [comment]
@dvdplm Yes, it's absolutely used. Running `cargo update` as indicated above will suffice. It's generally a good idea to read the very first comment :slightly_smiling_face:

**Comment by dvdplm** [comment]
So the bug is in a transient dependency? If I want to avoid a blanket `cargo update`, which dependency do I need to update?

**Comment by jhpratt** [comment]
No, it's not a bug of any kind; your indirect dependencies are just outdated. `version_check` is the dependency you need to update, since you don't want to update everything for some reason.

**Comment by dvdplm** [comment]
> `version_check` is the dependency you need to update, since you don't want to update everything for some reason.

Lovely, thank you. Generally big projects wants to avoid blanket `cargo update` to avoid random breakage.

**Comment by ffactory-ofcl** [comment]
I'm not an expert but if your project breaks when you run cargo update, doesn't that mean you may need to fix your Cargo.toml? 🤔 
`cargo update` just updates the Cargo.lock to the newest versions and if Cargo.toml has the correct versions, a clean install & cargo run should work (and thus cargo update on an existing install should work too)

**Comment by dvdplm** [comment]
Yeah, that's the theory and when it works, it's nice. When it doesn't it's a bit nasty: now you have 300 minor versions updated and figuring out which one didn't respect semver properly can be tricky.

**Comment by samuela** [comment]
> No, it's not a bug of any kind; your indirect dependencies are just outdated. version_check is the dependency you need to update, since you don't want to update everything for some reason.

This sounds like a bug that `time` does not specify the right minimum version for `version_check`. Why is `cargo update` really necessary here?

**Comment by MrTact** [comment]
It's not a `time` bug. It's a bug in the build system -- it relies on an updated version of cargo that makes a formerly private function public.
