### ISSUE TITLE
Upgrade to quickcheck 1.0

### ISSUE THREAD

**Issue by jhpratt** [time-rs/time#302]
The time crate should upgrade the quickcheck dependency to 1.0 prior to time's 0.3 release. The API is largely similar, but there are some changes. Notably, it is no longer possible (for the time, see BurntSushi/quickcheck#267) to generate a value within a given range. This can be worked around with the following function. It has some limitations with regard to overflow within the type, but I don't believe that should be an issue for any values used in the time crate.

```rust
fn arbitrary_between<T>(g: &mut Gen, min: T, max: T) -> T
where
    T: PartialOrd
        + AddAssign
        + Add<Output = T>
        + Sub<Output = T>
        + Rem<Output = T>
        + Arbitrary
        + Copy,
{
    #[allow(clippy::eq_op)]
    let zero = min - min;

    let range = max - min;
    let mut within_range = T::arbitrary(g) % range;

    if within_range < zero {
        within_range += range;
    }

    within_range + min
}
```

One thing I noticed in the documentation that I didn't before (I'm not sure if it was present or not and can't be bothered to check) is that the `Gen::size()` method _does not need to be used_, as all types in the time crate have a constant size; the example used as a use case is `Vec`, which most certainly does not. As such, the entire `foo_respects_generator_size` and `test_generator_size!` bit can be dropped, I believe.

This should likely be done in coordination with #299, though it's not strictly necessary. That change by itself will be nearly trivial.

cc @emlun if you're interested with your macro magic. No big deal if not.

**Comment by emlun** [comment]
I'll take a look!

**Comment by jhpratt** [comment]
Whoops, forgot to leave a second comment! I have it pretty much all figured out, as I stripped out the bit mentioned in the original issue.

I believe I found a bug in quickcheck, but have yet to file an issue on it. Other than that I think everything works.

Thank you, though!

**Comment by emlun** [comment]
Oh, okay. :slightly_smiling_face: In that case I'd gladly review the changes instead, if you want. Let me know if you need anything!

**Comment by jhpratt** [comment]
Ok! I'll let you know when a PR goes up if you'd like.
