### ISSUE TITLE
Document that OffsetDateTime::from_unix_timestamp returns a date with the UTC time zone

### ISSUE THREAD

**Issue by daboross** [time-rs/time#305]
From the documentation, many of the (non-deprecated) constructors on `OffsetDateTime` document what timezone the date they return is in. However, `OffsetDateTime::from_unix_timestamp` doesn't.

Naively, I could imagine assuming this returns either said unix time with a local timezone, or with the UTC timezome - and while I think UTC time makes the most sense, it would be nice to have this documented to be sure.

**Comment by jhpratt** [comment]
Can do. UTC is the only thing that makes sense to me, but I see how others may mistakenly believe the contrary.
