### ISSUE TITLE
Add `doc(html_root_url)` so links from external crates to `time` work

### ISSUE THREAD

**Issue by SergioBenitez** [time-rs/time#314]
See https://doc.rust-lang.org/rustdoc/the-doc-attribute.html#html_root_url.

**Comment by jhpratt** [comment]
While this has been recommended by the API guidelines for quite a while, this recommendation is pending removal; it has already completed FCP and just needs merging. So unless there is something everyone has missed, including during the announced FCP, I'm inclined to close this.

[Reference](https://github.com/rust-lang/api-guidelines/pull/230)

**Comment by SergioBenitez** [comment]
I've expressed my thoughts in the issue. For concreteness, links to time are [currently broken in the development docs](https://api.rocket.rs/master/rocket/form/trait.FromFormField.html#provided-implementations) because this attribute is missing from `time`.

**Comment by jhpratt** [comment]
Ok, I'll wait for some further discussion to take place there. I will refrain from duplicating discussion as well.

**Comment by SergioBenitez** [comment]
It looks like the new-ish `-Zrustdoc-map` lets us fill in the URL on our side. As long as the docs are at `docs.rs`, this'll do. Thanks!
