### ISSUE TITLE
Faster serialization implementation

### ISSUE THREAD

**Issue by Plecra** [time-rs/time#315]
https://github.com/time-rs/time/blob/4bd26530c16dd9ac7d8f941123fab5d8abbad6c8/src/serde/mod.rs#L126-L129

The `Serializer::collect_str` method can be used with `format_args` to remove this `alloc` dependency

**Comment by jhpratt** [comment]
I'll definitely change this, but the human readable formats actually rely on std now due to the `io::Write` trait. As such, the alloc dependency will still be there. I am considering an internal change that would remove this limitation, though.
