### ISSUE TITLE
Format date into existing string

### ISSUE THREAD

**Issue by gyscos** [time-rs/time#328]
Currently two methods exist to format a date:
* `format()`, which allocates a new string
* `format_into()`, which writes into a `impl std::io::Write`.

The problem with taking a `impl std::io::Write` is that it isn't implemented for `String`. Indeed, a `std::io::Write` could potentially write arbitrary byte sequences, not just valid UTF-8. Is this the case for this implementation?

If not, could it maybe take a `impl std::fmt::Write`? This requires only printing valid utf-8 byte sequences, but that doesn't sound like a very restrictive requirement. And it would natively allow writing to a `String`.

The current workaround is to write to a `Vec<u8>`, then use `String::from_utf8`, which spends some time validating the sequence.

Is there a specific reason to work with `std::io::Write`?

**Comment by jhpratt** [comment]
It used to use `impl core::fmt::Write`. I forget the exact reasoning I made this change, but I'm fairly certain it was based on my personal experience using the previous API.

I will note that _yes_, it is possible to write a byte sequence that is not valid UTF-8. Doing this would require constructing the format description manually, as `time::format_description::parse` takes a string as a parameter (thus leaving only valid UTF-8 in the generated format description).

**Comment by jhpratt** [comment]
I don't see a way to implement this. As I noted before, the byte sequence does not have to be valid UTF-8. The only way to implement this would be create a string (and in doing so validating that it's UTF-8 or using replacement characters), which would be no different than doing this manually.
