### ISSUE TITLE
Unclear what the resulting century will be when parsing with %y

### ISSUE THREAD

**Issue by detly** [time-rs/time#332]
Consider:

```rust
fn main() {
    let time_str = "210101000000";
    let time_parsed = time::PrimitiveDateTime::parse(time_str, "%y%m%d%H%M%S").unwrap();
    println!("Result: {}", time_parsed.format("%Y"));
}
```

The first string contains the two digit year `21`. The output year is `0021` ie. 21 years into CE. Obviously there is a loss of information here; `time` has no idea if I mean 2021, 1921, or some even less likely date. Nonetheless the docs don't say anything about what century to expect (even C0 would be useful info). I wouldn't say it's a surprise, exactly, but libraries for other languages sometimes either have a "pivot" year as an argument (or baked in), to bring it into the 20/21st century.

I'm not sure what (if anything) you'd want to do about it functionally, but it might at least help people to document this.

**Comment by jhpratt** [comment]
In the lack of information, time assumes _nothing_. This means that if all that's provided is the last two digits, that is all that is known.

I could update the documentation, but no further releases are planned for v0.2 (the one yesterday was a bugfix). v0.3 is set to be released relatively soon, so I'm not sure what good updating the documentation at this point would do.

**Comment by detly** [comment]
It'll still be helpful going forwards. I get that it assumes nothing, but at a meta-level, a developer can't assume that *you* assume nothing, given the custom of other libs. If that makes sense.

Also there isn't a `std::Duration::from_years()` so getting from eg. `date!(21-01-01)` to `date!(2021-01-01)`, so getting from 21CE to 2021CE is not trivial.

**Comment by jhpratt** [comment]
My point is that with no further release planned, the change will _never_ hit docs.rs. Other libraries already rely on this assumption (I know cookie does for a fact).

`std::time::Duration` is not from this crate, but `time::Duration` intentionally does not provide years; not every year is the same length.

**Comment by detly** [comment]
> My point is that with no further release planned, the change will never hit docs.rs

Ah, I didn't understand that. Oh well.

> not every year is the same length.

Indeed. The problem is not adding a specific length of time, but restoring the context of the missing century information, which is a bit orthogonal to what a lib like `time` is doing. Nonetheless, it'd be nice if there was a more performant way of doing it vs. accessing multiple fields of the `*DateTime` struct through method calls, adding 2000 to the year, and reconstructing it with a fallible constructor.

**Comment by jhpratt** [comment]
I'll note that there will be a `Period` type in the future that will handle that sort of thing. I should create a tracking issue for that at some point.

The issue is that it's not trivial to add context back after it's taken away. It's for this reason that it's best to not do it in the first place imo. The only reason I even have support for the last two digits is because a significant number of people would likely ask for it.

**Comment by detly** [comment]
> It's for this reason that it's best to not do it in the first place imo

I agree, and will spare you our internal arguments about it :upside_down_face: My approach is to validate the input string, prepend `20` to it, and set a reminder for December 1st, 2099.

**Comment by jhpratt** [comment]
With the release of v0.3.0, this no longer applies.
