### ISSUE TITLE
Const evaluatable version of `time::format_description::parse`

### ISSUE THREAD

**Issue by paolobarbolini** [time-rs/time#333]
I really like the fact that 0.3 separates parsing of the format description from the uses of it, but it would be even more powerful if it were const evaluatable, that way a parsed format description could reside in a constant and be reused everywhere.

I haven't had much time to play with it, but despite the many limitations around const evaluation, it might still be possible to write a const version of this function. Here's my initial still early days attempt: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=3a6ab7b531f5a7cb1cfb5e4c131df1af

**Comment by jhpratt** [comment]
😉 https://time-rs.github.io/api/time/macros/macro.format_description.html
