### ISSUE TITLE
Cargo audit warning about stdweb being unmaintained

### ISSUE THREAD

**Issue by damccull** [time-rs/time#336]
Hello,

When running cargo audit on my project I'm getting the following warning:

```
Crate:         stdweb
Version:       0.4.20
Warning:       unmaintained
Title:         stdweb is unmaintained
Date:          2020-05-04
ID:            RUSTSEC-2020-0056
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0056
Dependency tree:
stdweb 0.4.20
└── time 0.2.26
```

This seems to indicate to me that the time crate is pulling in stdweb, which is unmaintained. Am I just doing this wrong or is this something I need to be concerned about and somehow mitigate?

**Comment by jhpratt** [comment]
Please search before creating an issue.
