### ISSUE TITLE
Case sensitivity modifier for format specifiers

### ISSUE THREAD

**Issue by acfoltzer** [time-rs/time#337]
It would be very useful to be able to control the case sensitivity of some of the format specifiers such as weekday and month names. This is useful when implementing specs that recommend case insensitivity for consumers of a format, such as the [HTTP caching spec](https://datatracker.ietf.org/doc/html/rfc7234#section-4.2). This example, starting with a deliberately lowercase `s`, fails to parse even though a cache ought to be able to accept it:

```rust
#[test]
fn parse_imf_fixdate() {
    let _ =
        PrimitiveDateTime::parse("sun, 06 Nov 1994 08:49:37 GMT", "%a, %d %b %Y %T GMT").unwrap();
}
```

I was unable to find documentation for the specifier syntax in `0.3`, but I don't see anything in the code regarding case sensitivity. This capability is important for our ability to move from `chrono` to `time`.

**Comment by jhpratt** [comment]
The current docs for the format description in 0.3 is [here](https://time-rs.github.io/book/api/format-description.html). I still need to update the in-crate docs and finish the rest of the book, of course.

You are correct that it's not currently possible to match case insensitively. I think this is a reasonable addition behind a `case_sensitive:{true|false}` modifier. Off the top of my head, I'm pretty sure this would be quite simple to implement, as the underlying functionality already exists to an extent.

**Comment by acfoltzer** [comment]
Thank you! Sounds great. No rush at the moment as I wrote a `logos` + `lalrpop` parser that builds an `OffsetDateTime` directly, but this seems like it'd be a nice feature to have for lighter-weight uses.

**Comment by jhpratt** [comment]
Actually going to go into quite a rabbit hole here. This request made me realize that the list of modifiers is not exhaustive, which requires the structs to be marked `#[non_exhaustive]`. Not an issue in and of itself, except that means users (including the macro) can no longer construct a modifier directly. So now I'm digging into a few patterns that have to be const-compatible 🤞🏽

**Comment by jhpratt** [comment]
Done in 7a05a42.
