### ISSUE TITLE
Unable to parse hour without minute component in 12-hour-format

### ISSUE THREAD

**Issue by puetzp** [time-rs/time#347]
Hey there,
first of all, congratulations on the release of v0.3!
I have one question that came up when I was running some tests and they failed. I skimmed the code base and found the relevant part:

```rust
impl TryFrom<Parsed> for Time {
    type Error = error::TryFromParsed;

    fn try_from(parsed: Parsed) -> Result<Self, Self::Error> {
        let hour = match (parsed.hour_24, parsed.hour_12, parsed.hour_12_is_pm) {
            (Some(hour), _, _) => hour,
            (_, Some(hour), Some(false)) if hour.get() == 12 => 0,
            (_, Some(hour), Some(true)) if hour.get() == 12 => 12,
            (_, Some(hour), Some(false)) => hour.get(),
            (_, Some(hour), Some(true)) => hour.get() + 12,
            _ => return Err(InsufficientInformation),
        };
        let minute = parsed.minute.ok_or(InsufficientInformation)?;
        let second = parsed.second.unwrap_or(0);
        let subsecond = parsed.subsecond.unwrap_or(0);
        Ok(Self::from_hms_nano(hour, minute, second, subsecond)?)
    }
}
```

I was basically trying to parse "5 AM" and from the code above I conclude that in order to be parsable as `Time` I would need to specify a `[minute]` component as well. Is it possible to allow parsing from a `[hour]` component alone?

Thank you in advance and keep up your great work on this crate!

**Comment by jhpratt** [comment]
Thank you! I'm certainly much happier with the design of 0.3 than 0.2.

I have considered this sort of thing in the past, as it's certainly something plausible. My concern was that it would be possible to just have "5" and get the hour — whether it's on a 12-hour clock or a 24-hour clock. It just felt like too little information to give a complete `Time`.

However, there isn't any technical reason I couldn't mandate the minute when the hour component does not provide AM/PM (so if it's just the plain 12-hour clock without specifying or the 24-hour clock in any situation). This would permit the narrow use case of "5 AM" and similar.

By the way, if you're trying to just parse "5 AM", you'll want `[hour padding:none]`, as the default padding is zeroes.

**Comment by jhpratt** [comment]
Just pushed a commit that adds this specific case. If _any_ of `hour_24`, `minute`, `second`, and `subsecond` are set, the conversion will fail, as I feel that it is not unambiguous in that case.

I'll likely cut a release with this and #346 Friday or Saturday.

**Comment by jhpratt** [comment]
Actually, I should add support for this to the macro now that I think of it.

**Comment by jhpratt** [comment]
Okay, that's better 😄 Both the `time!` and `datetime!` macro accept the same syntax with the same restriction.
