### ISSUE TITLE
Date::month_day is hidden from user in 0.3

### ISSUE THREAD

**Issue by DoumanAsh** [time-rs/time#357]
Subj.
Why? It would be more efficient for user to call this function once instead of doing it twice getting day and month separately

**Comment by jhpratt** [comment]
You can call `date.to_calendar_date()` which also provides you with the year. The `date.month_day()` method is an implementation detail.

**Comment by DoumanAsh** [comment]
`Date::to_calendar_date` performs more than I need as it needs to compute year.
Considering that `month_day` just returns two integers I'm not sure why it is implementation detail?

You even left original docstring >/// Get the month and day. This is more efficient than fetching the components individually.
Well I suppose it is your choice of removing useful API

**Comment by jhpratt** [comment]
The compiler is likely smart enough to optimize out the year access, given that it's only a bitshift.

It is an implementation detail because the current implementation uses an algorithm that calculates both simultaneously; that may not always be the case.

**Comment by DoumanAsh** [comment]
> The compiler is likely smart enough to optimize out the year access
Trusting compiler to do job right is the worst thing you can do.
If you can write code without needing compiler to optimize it that's only better

**Comment by jhpratt** [comment]
>  is the worst thing you can do.

Please be respectful.

I have stated that it's an implementation detail. There is no guarantee that, in the future, `.month_day()` will be more efficient than obtaining the components separately. If it's not in the public API, it's not guaranteed.

If you believe there is better code that does not involve exposing implementation details, feel free to create a pull request. There are benchmarks that can be expanded on if you have a particular use case you'd like monitored.
