### ISSUE TITLE
`OffsetDateTime::format` (and `::format_into` and `::parse`) should allow `?Sized` for the `Formattable` (and `Parsable`) bound

### ISSUE THREAD

**Issue by Arnavion** [time-rs/time#359]
https://github.com/time-rs/time/blob/d700977ce9bc34013ee9841e122edbc807f410e4/src/offset_date_time.rs#L808

This **can't** be used like this:

```rust
const FORMAT: &[FormatItem<'_>] = time::macros::format_description!("...");

time.format(FORMAT)
```

... even though `[FormatItem<'_>]: Formattable` and thus `&[FormatItem<'_>]` is `&impl Formattable`. This is because the `impl Formattable` bound disallows `!Sized` types like `[FormatItem<'_>]`

It should be `pub fn format(self, format: &(impl Formattable + ?Sized)) -> Result<String, error::Format> {`, and the same for `format_into` and `parse`

Compare `foo` and `foo2` in   https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=72a25a6049efc8d16f374a460cfa0dce

---

Workaround: write `time.format(&FORMAT)` instead, which works through the blanket impl for `Deref`.

**Comment by jhpratt** [comment]
The change, as you saw, is trivial. I don't believe this will introduce any compatibility concerns as it only _permits_ unsized parameters rather than requiring them. The methods only delegate to the trait, but I'd like to be sure that I won't want to change something in the future that would require the parameters to be sized.

**Comment by Arnavion** [comment]
>but I'd like to be sure that I won't want to change something in the future that would require the parameters to be sized.

So do you need something from me? Or are you saying you don't want to merge the PR?
