### ISSUE TITLE
`OffsetDateTime + Duration` behavior

### ISSUE THREAD

**Issue by L117** [time-rs/time#364]
It would be nice to have this behavior documented somewhere.
Can this operation overflow? If so, will it panic? Will it wrap or saturate value?

It would also be nice to have `checked_*`, `saturating_*` and `wrapping_*` families of methods (with duration operand).

**Comment by L117** [comment]
I have started working on this.

**Comment by jhpratt** [comment]
Would you like to do take on the saturating methods as well? The actual implementation should be trivial; it's the documentation and tests that'll take a short bit.

**Comment by L117** [comment]
Sure. Actually, I almost finished implementation, docs and tests. This is how I found #384 (:

**Comment by jhpratt** [comment]
Awesome. I'll hold off on changing the internals of `OffsetDateTime` until then.

**Comment by L117** [comment]
Also, what do you think about adding `MIN`/`MAX` constants for `PrimitiveDateTime`, `MAX` constant for `Time` and `min_for_offset`/`max_for_offset` inherent const functions for `OffsetDateTime`, at least with `pub(crate)` visibility? They are not strictly required, but I would like to have them in `saturating_*` methods rather than literal values (via macros):
```rust
pub const fn saturating_add(self, duration: Duration) -> Self {
    if let Some(datetime) = self.checked_add(duration) {
        datetime
    } else if duration.is_negative() {
        Self::MIN
    } else {
        Self::MAX
    }
}
```

**Comment by jhpratt** [comment]
For `PrimitiveDateTime` `pub const {MIN,MAX}` is fine. For `Time`, let's keep it `pub(crate)` (you can add `MIN` for symmetry if you'd prefer).

Given that I'm going to at least attempt, and likely migrate towards, an implementation that stores the value in the local offset and not UTC, I don't think those methods are necessary for `OffsetDateTime`. Honestly it'd be fine if you just stubbed them out — the documentation and tests are where the real work is at, with the latter being nearly identical to `PrimitiveDateTime`. If you go that route, just put `#[ignore]` on the relevant tests for the time being so CI doesn't fail.

**Comment by L117** [comment]
Got it. Actually I can just do `PrimitiveDateTime::MIN.assume_utc().replace_offset(self.offset)` for now. With current ranges, this will do the same thing as `min_for_offset`.

**Comment by jhpratt** [comment]
Closing as implemented. Thanks again.
