### ISSUE TITLE
Date::parse now doesn't accept String

### ISSUE THREAD

**Issue by aldanor** [time-rs/time#365]
(Other `parse` methods as well, I think)

While it used to accept it and now doesn't, there's no real reason for it other than some method signatures changing during the big rewrite - so it needlessly breaks some code that used to work in 0.2.

The solution is simple: take `impl AsRef<str>` instead of `&str`.

**Comment by jhpratt** [comment]
Is there some reason you can't just do take a reference to the string? The intent was to prevent users from needlessly moving or cloning the value.

**Comment by aldanor** [comment]
There's nothing sinister in doing `Date::parse(something_that_returns_a_string())`, no? I think there's tons of valid use cases that shouldn't really be 'prevented' from a 3rd party library's standpoint.

If users want to move a string, ok then - it means they don't need it anywhere else anymore - in which case there's no difference in passing a ref or moving it since it's going to be dropped shortly anyway.

Taking `&str` means "give me a reference and nothing else, up to you to extract it"; `impl AsRef<str>` is more like "give me something that can produce a reference, don't care what it is really" which is far more ergonomic. (my 2c, anyway)
