### ISSUE TITLE
timezone support for strftime

### ISSUE THREAD

**Issue by rohitjoshi** [time-rs/time#37]
When I use  time::strftime("%Y-%m-%d %H:%M:%S %Z", &time::now()).unwrap(),  I get timestamp without timezone.   Here is output I get.  2014-12-18 12:32:31

How do I get timezone printed?  

Here is equivalent python code

import datetime
import pytz
d = datetime.datetime.now(pytz.timezone("America/New_York"))
d.strftime("%Y-%m-%d %H:%M:%S %Z")

'2014-12-18 12:41:19 EST'

**Comment by afandian** [comment]
It looks like named timezones are just ignored in [parse.rs](https://github.com/rust-lang-deprecated/time/blob/master/src/parse.rs#L247). The comment suggests that the C's original `strptime` is broken. 

```
println!("{}", time::strptime("Tue Jan 01 12:37:48 GMT 2013", "%a %b %d %T %Z %Y").unwrap() == 
               time::strptime("Tue Jan 01 12:37:48 ETC 2013", "%a %b %d %T %Z %Y").unwrap());
=> true
```

However using time offsets does work

```
println!("{}", time::strptime("Tue Jan 01 12:37:48 +00:00 2013", "%a %b %d %T %z %Y").unwrap() == 
                   time::strptime("Tue Jan 01 12:37:48 +05:00 2013", "%a %b %d %T %z %Y").unwrap());
```

My workaround's going to be string replacement (for now). 

Perhaps there could be another parse function that does what's expected?

**Comment by jhpratt** [comment]
My current thought is to drop the "support" for `%Z` in 0.2. That specific formatting option requires knowledge of the actual timezone, not just the offset, and this info isn't stored anywhere. Parsing _may_ happen, though it isn't likely.

**Comment by jhpratt** [comment]
The minimal support for `%Z` has been completely dropped for 0.2.

**Comment by jhpratt** [comment]
Closing in favor of #193, which would include this.
