### ISSUE TITLE
leap seconds

### ISSUE THREAD

**Issue by est31** [time-rs/time#377]
I was wondering about adopting the `time` crate for two libraries that I maintain, rcgen and yasna. However, I've seen that there is no handling of leap seconds in `time`. I'm still investigating how important they are for rcgen and yasna use cases, but generally single seconds [can mean a lot](https://community.letsencrypt.org/t/2021-06-08-certificate-lifetime-incident-valid-for-an-extra-one-second/153426). Even if yasna and rcgen benefit only little from leap seconds, I think it's important to have them in a general purpose time handling library. Not everyone uses google's smeared seconds standard :).

**Comment by jhpratt** [comment]
Leap seconds inherently rely on the time zone database, which is tracked in #193. Properly handling them is extremely difficult; chrono doesn't even handle them properly.

As an aside, the issue with LetsEncrypt has nothing whatsoever to do with leap seconds.
