### ISSUE TITLE
Macros use hardcoded package name instead of referring to crate

### ISSUE THREAD

**Issue by Drevoed** [time-rs/time#379]
![image](https://user-images.githubusercontent.com/53709100/139675531-afd09fb7-ab05-4984-80b4-341e19f2ba52.png)
This will not compile if you have a dependency defined like this
```toml
time_03 = { package = "time", version = "0.3", optional = true, features = ["macros"] }
```

**Comment by Drevoed** [comment]
Or is there no way to bypass this?

**Comment by jhpratt** [comment]
This was discussed not too long ago in #356. Unfortunately there is no API equivalent of `$crate` for proc macros, let alone for another crate. Due to the plausible nature of using `time` as an identifier, tokio's workaround isn't workable here. As such, there is no way around this, unfortunately.
