### ISSUE TITLE
Add `ECMAScript Date Time` format description

### ISSUE THREAD

**Issue by malobre** [time-rs/time#383]
When working with a web frontend you may need to parse a date, they are usually formatted by the [`toISOString()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString) function.
> [This function return a string] which is always 24 or 27 characters long (YYYY-MM-DDTHH:mm:ss.sssZ or ±YYYYYY-MM-DDTHH:mm:ss.sssZ, respectively).

[ECMAScript Date Time String Format](https://tc39.es/ecma262/multipage/numbers-and-dates.html#sec-date-time-string-format)

**Comment by jhpratt** [comment]
I don't know if you noticed this, but the text on MDN doesn't match the text of the specification. MDN says it has to be 24 or 27 characters (implicitly always using `Z`), but the spec says `±HH:MM` is also valid. This format can definitely be added, but this uncertainty needs to be resolved in my opinion.

**Comment by malobre** [comment]
It is not an error, the format support timezones but this particular function returns only UTC,  from MDN:
> The timezone is always zero UTC offset, as denoted by the suffix "Z".

**Comment by jhpratt** [comment]
Yes, but per the specification:

>  `Z` is the UTC offset representation specified as "Z" (for UTC with no offset) or an offset of either "+" or "-" followed by a time expression HH:mm (indicating local time ahead of or behind UTC, respectively)

MDN is also injecting its own viewpoint that it has to be a fixed number of characters, which cannot be reconciled with the spec.

**Comment by jhpratt** [comment]
Marking this as blocked pending a resolution of the previous concern.

**Comment by malobre** [comment]
In my case I ended up using the `RFC3339` format description.
I did some research and there seem to be only one case where a `ECMAScript Date Time` string will not be RFC3339 compliant: expanded years with 6 digits.

An ISO8601 format description would handle `ECMAScript Date Time` and be useful to more people.
