### ISSUE TITLE
`PrimitiveDateTime::assume_offset` may overflow

### ISSUE THREAD

**Issue by L117** [time-rs/time#384]
`assume_offset` calls `offset_to_utc`, which does not perform checks.
https://github.com/time-rs/time/blob/be29bb35f89524a2c9cd3738fe6dce1c5644e59e/src/primitive_date_time.rs#L531-L553
Sample code to reproduce:
```rust
use time::macros::{datetime, offset};

fn main() {
    let datetime = datetime!(-999999 - 01 - 01 00:00);
    let datetime = datetime
        .assume_offset(offset!(+10:00))
        .replace_offset(offset!(+00:00));
    assert_eq!(datetime.year(), -1_000_000);
}
```
In particular, this means methods `OffsetDateTime::checked_{add,sub}` contain some unexpected behavior when date value is out of range `Date::MIN ..= Date::MAX`. And their doctests also have overflowed values (Shame on me for not noticing this earlier).

I can write a PR, but what exactly should it change?

**Comment by jhpratt** [comment]
Hey, for once I actually noticed this issue previously! See #307 for a detailed description and possible solutions. I previously decided the status quo was acceptable. I'm open to thoughts on other possible solutions (including drawbacks), given that I doubt many people saw #307 at the time.

**Comment by L117** [comment]
Well, personally I'd always choose correctness over convenience. Luckily, it seems we don't have to choose this time.

For now, our options are:
1. We leave everything as-is. The obvious drawback is that we leave this bug open. Actually, a whole family of bugs.
2. We make some functions non-`const`. This is one kind on inconvenience as they will not be usable within const expressions anymore, 
3. We make API fallible. This is another kind of inconvenience, as users will have to unwrap value one way or another. And there's no way to unwrap in const expressions.
4. We can wait for stabilization of `const_panic`. It is already in beta so, hopefully, it will soon be in stable. With `const_panic` we have two more options:
   1. Add functions for checked conversions and make existing API depend on them.
   2. Replace existing conversions with checked ones, as unwrapping will be possible within const expressions.

   The only drawback I see is that we'll have to bump MSRV. 

Personally, I'd pick 4-th option. Bumping MSRV for the sake of fixing bugs seems reasonable. 

Whether it should be option I or II is questionable. If `unwrap` will instantly get `const` qualifier, then I see a little sense in keeping a lot of similar functions (**forever**) just to save users from writing it. These functions are fallible, so it should be obvious that they are, and users should explicitly unwrap the value if they are completely sure these functions have succeeded or don't care if they failed. But this is only my opinion.

**Comment by jhpratt** [comment]
(4) is precisely what I was thinking, but with a hack (array indexing) to simulate const panic before it's been on stable for six months (that'll occur on 2022-06-02). Once I insert the check I'd just note that the function can panic in the documentation.

Time 0.4 is a long ways off, but making the function fallible is something that _might_ be worth considering.

**Comment by L117** [comment]
Oh, you mean something like
```rust
macro_rules! const_unwrap_opt {
    ($e:expr) => {{
        if let Some(value) = $e {
            value
        } else {
            [][0]
        }
    }}
}
```
This will do.

**Comment by jhpratt** [comment]
Yeah, something to that effect. It's not pretty but it works.

**Comment by L117** [comment]
So, your intent is to allow out-of-range values in internal code?

**Comment by jhpratt** [comment]
That's correct. There's nothing that actually restricts or makes it unsafe to do so; the data structure is more than capable of handling the extra day on each end. It's logical that a user would want an in-range date in the stored offset. We just need to make sure that it is in-range when _changing_ the offset.

**Comment by L117** [comment]
Then current `checked_add`/`checked_sub` implementations for `OffsetDateTIme` are not valid. E.g. when duration is 0 or some really small value. Because they use internal `self.utc_datetime` and depend on checked arithmetic of `PrimitiveDateTime`, which assumes that `PrimitiveDateTime` is always in it's range. This can be resolved by applying offset (thus getting local `PrimitiveDateTime` that *is* in range), doing arithmetic and then converting back.

Another drawback is that there will be some `OffsetDateTime` values that cannot be converted back to `PrimitiveDateTime` (UTC).

**Comment by jhpratt** [comment]
I've been thinking about this some more. I'd like to mull this over for a bit, as it seems like the checks will cause more hassle than it's worth. The edge cases are likely quite rare, so I'll have to weigh the different options.

Right now, I'd say I'm leaning _slightly_ towards not promising behavior at the edges, which would allow significantly faster operations in a number of cases.

**Comment by L117** [comment]
If we dig a little deeper...  Is there a reason why `OffsetDateTime` stores `utc_datetime` + `offset` and not something like `offset_datetime` + `-offset`? If we make this change, we will get rid of computations in all the getters, will not get out of `PrimitiveDateTime`'s range, will be able to strictly define minimum/maximum values, move conversions to methods that do conversions (Like `to_offset`), thus are expected to not be always cheap and may be falible, maybe more. It sort of screams to be changed (: 

Forgive me If I don't see something obvious that prevents doing all of this.

**Comment by jhpratt** [comment]
One of the options presented in #307:

> Store the internal `PrimitiveDateTime` in terms of the attached `UtcOffset`, not UTC. While feasible for `OffsetDateTime`, this could prove _disastrous_ down the road when it comes to an implementation using tzdb, as similar behavior would be expected. This would then mean that _it is not possible_ to determine the actual moment in time that should be represented, as clocks change on occasion (notably daylight saving time), causing ambiguities in the local time.

For `OffsetDateTime` specifically it is possible (and was actually what was done originally iirc). But all that does is kick the can down the road, as it would still need to be addressed for `ZonedDateTime` or whatever it ends up being called.

**Comment by L117** [comment]
I spent some time reading `tz-how-to.html` from `tzdb`. Now I see what do you mean.
And it seems I have run out of options.

**Comment by jhpratt** [comment]
Exactly — it's a tricky issue with no obvious solution. Of course the temporary fix will be #386, but beyond that I'll probably require a proper "solution" that deliberately ignores externally mandated bounds.

**Comment by L117** [comment]
Actually, we can do something to make this work with `tzdb`.

Both `PrimitiveDateTime` and `OffsetDateTime` have inclusive range from `-999999 - 01 - 01 00:00:00.0` to `999999 - 12 -31 23:59:59.999999999`. We can limit future `ZonedDateTime` to the same range of values. Then, do computations in terms of UTC datetime (With possible overflow, just like in `OffsetDateTime`), convert timestamp to local datetime and see whether it fits in aforementioned range or not. If it fits, then ``checked_*` operation succeeds, otherwise - fails.

I have not checked the whole `tzdb`, but from a few records that I have seen, it seems overflow will be within 2 days range, so there should be no problems.

**Comment by jhpratt** [comment]
That sounds like it should work even in edge cases. With regard to tzdb, I'd be astounded if anywhere had an offset of more than 24 hours at any point in history. The current range is UTC–12 to UTC+14.

I'll need to document this approach in the tzdb tracking issue. I'll _probably_ switch how `OffsetDateTime` stores the data internally, though that'll rely on the output of benchmarks. I suspect they will overwhelmingly improve. In the meantime I need to review your PR fixing the bug.

**Comment by jhpratt** [comment]
I'm going to close this as intentional (described earlier in this issue). That said, I am going to investigate switching the internal representation.
