### ISSUE TITLE
Support for parsing/formatting as RFC-3339 with Serde

### ISSUE THREAD

**Issue by sazzer** [time-rs/time#387]
Issue #232 has added support for parsing and formatting timestamps using the RFC-3339. However, as best as I can tell, it only supports this in explicit code. It would be useful if this was supported in the Serde feature as well.

For example, instead of needing to do:
```
#[derive(Serialize)]
struct SomeResponse {
    pub some_timestamp: String
}
.....
SomeResponse {
    some_timestamp: value.format(time::Format::Rfc3339).expect("Failed to format value")
}
```

I could just do:

```
#[derive(Serialize)]
struct SomeResponse {
    #[serde(with = "time::serde::rfc3339")]
    pub some_timestamp: OffsetDateTime
}
.....
SomeResponse {
    some_timestamp: value
}
```

**Comment by jhpratt** [comment]
Yeah, this is doable.

**Comment by jhpratt** [comment]
This should be completed (sans tests) on the `serde-rfc3339` branch. I _will not_ be releasing this until [weak feature dependencies](https://github.com/rust-lang/cargo/issues/8832) has been on stable for the requisite amount of time, as doing so would mean anyone using a fair number of APIs would pull in serde for no apparent reason.

**Comment by mzabaluev** [comment]
> as doing so would mean anyone using a fair number of APIs would pull in serde for no apparent reason.

I'm not sure I understand the concern here. The whole mod `serde` is gated by the `serde` feature, use of `time::serde::rfc3339` further needs `parsing` and `formatting`, hence `std` (note this could be eased to `alloc` by #400). But anyone using this helper module must be needing serde anyway, aren't they?

**Comment by jhpratt** [comment]
I have a plan to get this to work. I am just working on something else first.

**Comment by jhpratt** [comment]
I thought about putting this behind the `serde-human-readable` flag, but that would require the default serialization to be human readable just to support the attributes. As a result, I decided to put this behind a new `serde-well-known` feature flag.

This is on main now — both RFC3339 and RFC2822. Tests will be added for this soon.

**Comment by jhpratt** [comment]
Not yet, no. It was just merged recently. There be a release soon-ish once some other changes get finalized.
