### ISSUE TITLE
Getting the `PrimitiveDateTime` (`utc_datetime`) component of `OffsetDateTime`?

### ISSUE THREAD

**Issue by Twixes** [time-rs/time#395]
Hey! In my application I want to expose two timestamp data types: one with time zone information and one without (assumed to be UTC). I thought that the `OffsetDateTime` and `PrimitiveDateTime` structs respectively would fit this model ideally, but I haven't found a way to access `OffsetDateTime`'s `utc_datetime` field (which is the `PrimitiveDateTime` backing it), and there's no `PrimitiveDateTime::now_utc()` either, so it seems that there's actually no way for me to use `PrimitiveDateTime`.
I can wrap `OffsetDateTime` in a `PrimitiveDateTime`-like newtype for differentiation (e.g. so that my serialization/deserialization trait implementation knows when it's needed to encode `offset`)… but that'd be a lot of boilerplate.
Why not just expose `utc_datetime`? Or am I missing something?

**Comment by Twixes** [comment]
Actually scratch that. I see that `OffsetDateTime` includes many useful methods that `PrimitiveDateTime` doesn't, so the practicality of the latter is really limited anyway. I'll work around this using `OffsetDateTime` only.

**Comment by jhpratt** [comment]
Yeah, the two structs are quite different (and for good reason). This has been requested a couple times recently, but I feel that using `.date()` and `.time()` are sufficient for those that want to do this. The internal representation isn't guaranteed, either.
