### ISSUE TITLE
Allow formatting of durations as "humantime"

### ISSUE THREAD

**Issue by thomaseizinger** [time-rs/time#396]
It would be nice if the `time` crate came with a way of formatting a `Duration` similar to this crate: https://docs.rs/humantime/2.1.0/humantime/fn.format_duration.html

Is something like this in scope?

**Comment by jhpratt** [comment]
So long as it's only formatting and not parsing, `impl Display for Duration` would be accepted. It doesn't need to be a wrapper struct (not sure why they did it that way).

**Comment by thomaseizinger** [comment]
> So long as it's only formatting and not parsing, `impl Display for Duration` would be accepted. It doesn't need to be a wrapper struct (not sure why they did it that way).

Would `impl Display` not a bit too opinionated? I was thinking of something like:

```rust
impl Duration {
	fn display_human_readable(&self) -> DisplayAdaptor<'_>;
}
```

This is analogous to https://doc.rust-lang.org/std/path/struct.Path.html#method.display.

**Comment by jhpratt** [comment]
`impl Display` would be the idiomatic thing to do. `Path::display` exists because `Path` isn't guaranteed to be UTF-8, so it can't `impl Display`, as that would mean it could become a `String` (which _must_ be UTF-8).

**Comment by thomaseizinger** [comment]
Copy that.

I'll look into submitting a PR!

**Comment by L117** [comment]
They probably did a wrapper struct for a number of reasons:
1. You can't implement external trait for external type.
2. Structs are easily composable with `format!(...)` macro, or at least easier than functions. And you can avoid `String` construction.
3. There's more than one human readable representation and it is not clear which one should be preferred.

**Comment by jhpratt** [comment]
Didn't even notice that it takes a struct that it doesn't control.

It should be noted in the docs that the format should not be relied upon, however.

**Comment by thomaseizinger** [comment]
Do we also want to support parsing via `FromStr`?

**Comment by jhpratt** [comment]
No, precisely because the format should not be relied upon.

**Comment by jhpratt** [comment]
Hey @thomaseizinger, any interest in creating a PR for this? If not I'll likely go ahead and do it.

**Comment by thomaseizinger** [comment]
> Hey @thomaseizinger, any interest in creating a PR for this? If not I'll likely go ahead and do it.

I am but didn't yet find the time to do it, sorry :/
Please feel free to go ahead!

**Comment by jhpratt** [comment]
No problem! I just wasn't sure if it was something you had your heart set on for whatever reason.

**Comment by jhpratt** [comment]
Done.
