### ISSUE TITLE
Add RFC2822 well-known format description 

### ISSUE THREAD

**Issue by agraven** [time-rs/time#399]
RFC2822 formatted dates are used in many places in web contexts, one of the more noteworthy of those being `Date` headers in the HTTP protocol. An example of a date in this format could be `Fri, 21 Nov 1997 09:55:06 -0600`.

As an additional note, the `chrono` crate has 2822 as a well known format, and adding it to `time` could be a big help to those interesting in migrating to `time`.

[The RFC2822 specification](https://datatracker.ietf.org/doc/html/rfc2822)

**Comment by jhpratt** [comment]
A PR implementing this would be accepted. From quickly looking at the spec, it should largely be able to be parsed using pre-existing components.
