### ISSUE TITLE
More fine-grained feature gates for formatting methods

### ISSUE THREAD

**Issue by mzabaluev** [time-rs/time#400]
It would be good to get a subset of the formatting functionality available on no-std targets. On the surface, the `format` methods can be changed to return `alloc::string::String` without breaking the current API. Also, #375 discusses formatting into a `&mut impl core::fmt::Write`, which would require neither `std` nor `alloc`.

Consider the feasibility of introducing more fine-tuned formatting feature gates to decouple availability of these methods from the requirement of `std`:

```
[features]
formatting = ["formatting-alloc", "std", "itoa/std"]  # full API including format_into
formatting-alloc = ["formatting-core", "alloc"]  # for format
formatting-core = ["itoa"]  # for formatting into &mut fmt::Write
```

**Comment by mzabaluev** [comment]
In a future backward-incompatible release, the `formatting` feature could be redesigned to be orthogonal to `alloc`/`std` and enable methods in combination with those:

* `#[cfg(and(feature = "formatting", feature = "alloc"))]` would enable `format`;
* `#[cfg(and(feature = "formatting", feature = "std"))]` would enable `format_into`;
* `#[cfg(feature = "formatting")]` would only enable `format_into_fmt`.

**Comment by jhpratt** [comment]
The `formatting` feature currently relies on `std`, so that change by itself is not breaking. I haven't had time to look at this in further detail.


cc @CryZe as I know you looked into this a bit.

**Comment by jhpratt** [comment]
As this was predicated on support for `fmt::Write`, closing for the time being. It may be reopened if necessary once support for `fmt::Write` lands (there's no timeframe for this).
