### ISSUE TITLE
API for generating format_descriptions that doesn't rely on alloc and can be used in const contexts?

### ISSUE THREAD

**Issue by alex** [time-rs/time#402]
Hello! I'm interested in using time's parsing support, however as best as I can tell, right now my choices are to either: a) Manually assemble a `[format_description::FormatItem]` by hand, which is very verbose, b) use `format_description::parse` which isn't `const` (and therefore would need `once_cell`/`lazy_static`) and requires `alloc`.

I think `time` would benefit from an API in the middle ground. So far my best idea is a public `parse_item` API, that would let you do something like:

```rust
const MY_FORMAT: &[FormatItem] = [
    FormatItem::parse_item("[year]"),
    FormatItem::parse_item("-"),
    FormatItem::parse_item("[month]"),
    FormatItem::parse_item("-"),
    FormatItem::parse_item("[day]"),
]
```

**Comment by alex** [comment]
In a fit of emberassment, I have just discovered https://docs.rs/time/0.3.5/time/macros/macro.format_description.html, which seems to solve my problems!

I suspect what's _actually_ needed is more cross-linking or examples using this in the docs.

**Comment by jhpratt** [comment]
Confirming that the macro is what you want. Documentation absolutely needs work; I just have other priorities (and have for quite a while).
