### ISSUE TITLE
Build fails on macos with feature `unsound_local_offset` 

### ISSUE THREAD

**Issue by pando85** [time-rs/time#408]
```
  --> /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/time-0.3.5/src/sys/local_offset_at/unix.rs:129:49
    |
129 |     if !cfg!(unsound_local_offset) && !matches!(process_is_single_threaded(), Some(true)) {
    |                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope
```

Function `process_is_single_threaded` is only defined for linux systems.

**Comment by jhpratt** [comment]
I believe this is already fixed on main. Even if not, it's not sufficient impetus for a release due to the statement in the documentation.

**Comment by ulwlu** [comment]
it would be great if even patch-version can be released because tracing-subscriber depends on this to log timestamp.

**Comment by jhpratt** [comment]
There will be a release in the near future. It's the holidays; I have other priorities.

**Comment by ulwlu** [comment]
sure, sorry i didn't mean to rush you. glad if you have a plan, coz i saw your comment 'it's not sufficient impetus for a release'. have a good holiday
