### ISSUE TITLE
`serde-human-readable` parsing breaks when decoding from non-borrowed strings (such as `serde_json::Value`)

### ISSUE THREAD

**Issue by lilyball** [time-rs/time#415]
Not a Contribution

The implementation of `serde-human-readable` deserializing returns an error if the input is not a borrowed string (as distinct from a `&str`). This means it works with `serde_json::from_str(s)` (assuming the JSON doesn't have something silly like `"2021\u002D12-15"`) but it doesn't work with `serde_json::from_value(v)`.

The culprit here is the fact that the `serde-human-readable` implementations all end up doing `<&str>::deserialize(deserializer)`. And unfortunately this means that it requires the deserializer to be able to deserialize a borrowed string. What you really want is a transient string, not a borrowed one, which means you need to use your own Visitor implementations (either that or just eat the string allocation, but that's wasteful). Unfortunately you can't just use `<Cow<str>>::deserialize(…)` as the `Cow` implementation always allocates (the `#[serde(borrow)]` attribute for doing zero-copy deserializing on a `Cow` field doesn't appear to have a publicly-exposed mechanism for doing this directly, though I suppose you could always make a `#[serde(transparent)]` newtype struct just to add the attribute).

This can be done with code that is structured like

```rust
struct Visit;
impl serde::de::Visitor<'_> for Visit {
    type Value = Date; // or whatever it is we're decoding
    fn expecting(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
        // oh look, we can have a better type error now!
        write!(formatter, "a string matching YYYY-mm-dd")
    }
    fn visit_str<E: serde::de::Error>(self, v: &str) -> Result<Self::Value, E> {
        // parse the &str here
    }
}
deserializer.deserialize_str(Visit)
```

This is mildly boilerplate-y, though it could be wrapped up in a macro if you like.

---

Reproduction (with `serde-human-readable`):

```rust
// This works
dbg!(serde_json::from_str::<time::Date>("\"2021-12-15\"")).ok();
// This fails
dbg!(serde_json::from_value::<time::Date>(serde_json::json!("2021-12-15"))).ok();
```

Output:

> ```
> [src/main.rs:87] serde_json::from_str::<time::Date>("\"2021-12-15\"") = Ok(
>     Date {
>         year: 2021,
>         ordinal: 349,
>     },
> )
> [src/main.rs:89] serde_json::from_value::<time::Date>(serde_json::json!("2021-12-15")) = Err(
>     Error("invalid type: string \"2021-12-15\", expected a borrowed string", line: 0, column: 0),
> )
> ```

Using the above `Visitor` pattern makes this work.

**Comment by jhpratt** [comment]
This was brought up a couple weeks ago and I plan on fixing it soon.

**Comment by jhpratt** [comment]
Fixed on main.

**Comment by georgmu** [comment]
Thank you for the fix.
Is there a time frame when this is included in a release?

**Comment by jhpratt** [comment]
It shouldn't be too much longer, relatively speaking. I'm working on an RFC for Rust right now, then I'm going to be reviewing the open pull requests in this repository. Once that's done I plan on creating a release.
