### ISSUE TITLE
Add subsecond rounding/truncation to Time, PrimitiveDateTime, and OffsetDateTime

### ISSUE THREAD

**Issue by xlambein** [time-rs/time#426]
Hi!

There's a feature in `chrono` that I found pretty useful: `round/truncate_subsecs`, which drops any subsecond precision from a time object.

Something like that (for `Time`):
```rust
fn truncate_subseconds(self) -> Self {
    let (h, m, s) = self.as_hms();
    Self::__from_hms_nanos_unchecked(h, m, s, 0)
}
``` 

I can make a PR if you think that's a good addition to `time`.

**Comment by xlambein** [comment]
More generally, could also be useful to support rounding and truncation by any `Duration`.

**Comment by jhpratt** [comment]
While I understand the motivation, I think a general rounding mechanism could be error-prone, as it's not always clear what the "base" point should be. Say I want to round to the nearest 37 seconds. It's not clear what that even means, especially given that it doesn't divide evenly into a day.

Truncating makes more sense, as it's just zeroing out a field. We can generalize this a bit more by adding the ability to replace any field (so long as it's trivial and obvious what it does). So I think I'd be okay adding `fn replace_nanosecond(self, nanosecond: u32) -> Result<Time, error::ComponentRange>` and similar. The caller could `.expect()` or `.unwrap()` on the call, which I would hope is optimized out.
