### ISSUE TITLE
Update documentation to mention that Instant does not have serde support

### ISSUE THREAD

**Issue by LeCyberDucky** [time-rs/time#431]
Hi, 

the documentation mentions, that the `serde` feature flag "Enables serde support for all types". This is misleading, since serde appears to be supported for all types, except `Instant`. As far as I understand, it makes sense to not have `serde` support for `Instant`, but this should be made clear in the documentation.

**Comment by jhpratt** [comment]
This can and should be done. It's already mentioned for `quickcheck`. You can submit a PR if you'd like (it's just a one line change) or I can get to this when I have time.
