### ISSUE TITLE
Please publish a v0.3.6 for improved local offset support

### ISSUE THREAD

**Issue by lilyball** [time-rs/time#433]
A number of local offset changes have been made since v0.3.5. What interests me in particular is bf5f830605112a167b8954698fdb58a381f4e962 which defers to `num_threads` for the OS support. The latest `num_threads` release supports `num_threads::is_single_threaded()` on macOS, but `time::UtcOffset::current_local_offset()` doesn't work (without `--cfg unsound_local_offset`) in v0.3.5.

**Comment by jhpratt** [comment]
Given my slowness in getting around to the open PRs and other improvements, I will look into whether the main branch is in sufficient state for a release. I know I'll need to update the changelog, but that's not a big deal by itself.

**Comment by jhpratt** [comment]
Done.
