### ISSUE TITLE
Support changing `OffsetDateTime`'s offset without changing the actual instant in time.

### ISSUE THREAD

**Issue by vincentdephily** [time-rs/time#437]
I'm parsing a unix timestamp and formatting it for the current timezone. This involves calling `replace_offset()` then `checked_add()` :

```rust
let fmt = format_description!("[year]-[month]-[day] [hour]:[minute]:[second] [offset_hour sign:mandatory]:[offset_minute]");
let offset_secs = Duration::new(offset.whole_seconds().try_into().unwrap(), 0);
OffsetDateTime::from_unix_timestamp(ts).unwrap()
                                       .replace_offset(offset)
                                       .checked_add(offset_secs)
                                       .unwrap()
                                       .format(&fmt)
                                       .unwrap()
```

It would be nice and less error-prone to have a `set_offset()` function that covers both operations.

It would be even nicer to have a `set_timezone()` function as this code is not DST-aware (and my program is multithreaded at this stage), but I understand that this is a much larger ask (#380).

**Comment by jhpratt** [comment]
Is this not `OffsetDateTime::to_offset`?

**Comment by vincentdephily** [comment]
D'oh ! Yes, `to_offset`, I looked for it hard but missed it. Sorry for the noise, closing.
