### ISSUE TITLE
Feature local-offset breaks (at least on illumos) in v0.3.6

### ISSUE THREAD

**Issue by nospam3089** [time-rs/time#438]
Previous versions of this crate builds without problems. See for example, in the working directory of a fresh clone of this repository:
```
% git checkout v0.3.5
HEAD is now at 6b8cdd3 v0.3.5 release
% cargo build --features=local-offset
   Compiling time v0.3.5 (/time)
    Finished dev [unoptimized] target(s) in 0.93s
```

With the upgrade to v0.3.6, compilation fails:
```
% git checkout v0.3.6
HEAD is now at 3ff4543 0.3.6 release
% cargo build --features=local-offset
   Compiling time v0.3.6 (/time)
error[E0609]: no field `tm_gmtoff` on type `tm`
  --> src/sys/local_offset_at/unix.rs:53:27
   |
53 |     let seconds: i32 = tm.tm_gmtoff.try_into().ok()?;
   |                           ^^^^^^^^^ unknown field
   |
   = note: available fields are: `tm_sec`, `tm_min`, `tm_hour`, `tm_mday`, `tm_mon` ... and 4 others

For more information about this error, try `rustc --explain E0609`.
error: could not compile `time` due to previous error
```

System information:
```
% rustc --print cfg
debug_assertions
target_arch="x86_64"
target_endian="little"
target_env=""
target_family="unix"
target_feature="fxsr"
target_feature="sse"
target_feature="sse2"
target_os="illumos"
target_pointer_width="64"
target_vendor="unknown"
unix
```

While I have not dug into what is causing this, I suspect the changes between the versions didn't get fully tested on illumos? I do not experience this problem when attempting an identical build on linux.

**Comment by jhpratt** [comment]
Confirmed. I'll look into this soon. I believe it's just an issue of getting the `#[cfg]` attributes correct.

> I suspect the changes between the versions didn't get fully tested on illumos?

That's correct. Illumos is not currently tested. I think I used to test Solaris but stopped when Rust renamed the target without warning or fallback.

**Comment by jhpratt** [comment]
Pending the outcome of the CI run (https://github.com/time-rs/time/runs/4948801105) I'm going to release a fix.

**Comment by jhpratt** [comment]
Published.
