### ISSUE TITLE
`Parsed::set_` and `Parsed::with_` methods return `Option<...>`s but always succeed

### ISSUE THREAD

**Issue by poliorcetics** [time-rs/time#439]
I haven't seen any plan to add a form of validation to these methods, is there any reason for them to not directly return `()` or `Self` ? That would avoid a fair bit or either `?` or `unwrap`s in some cases.

This change would obviously be a breaking one.

**Comment by jhpratt** [comment]
> is there any reason for them to not directly return `()` or `Self`?

Yes — validation may be added in the future. This is implied by the documentation:

> The setters _may_ fail if the value is invalid, though behavior is not guaranteed.

This is the case even setters like `set_weekday`, as the value may be inconsistent with other information already present.

**Comment by poliorcetics** [comment]
Thanks, I thought validation was only for the final `try_into`/`try_from`, not steps in between

**Comment by jhpratt** [comment]
Yeah, right now it is. But that's not guaranteed to always be the case. Early errors are generally a good idea.
