### ISSUE TITLE
time::serde::rfc3339 has unpredictable output length

### ISSUE THREAD

**Issue by Walther** [time-rs/time#440]
Opening a tracking issue here in the upstream, from a downstream issue in `tracing`.
Much more details in the corresponding issue in here: https://github.com/tokio-rs/tracing/issues/1729

Summary: `rfc_3339()` timestamps print with inconsistent length, with no zero padding at the end.

**Comment by jhpratt** [comment]
There is no guarantee of length beyond the fact that at least one digit will be present. This is consistent with the RFC3339 spec as written. It sounds like a custom format description should be used. This can guarantee a specific length.
