### ISSUE TITLE
Document how `OffsetDatetime::format` can fail

### ISSUE THREAD

**Issue by dbanty** [time-rs/time#444]
It's unclear to me how/why/when the [`format`](https://docs.rs/time/0.3.7/time/struct.OffsetDateTime.html#method.format) function can fail. If I'm using a well-known format (e.g., `Rfc2822`) _can_ this function fail? It seems, at a glance, that the underlying format function can only fail if parts of the format are missing.

**Comment by jhpratt** [comment]
How it can fail depends on the format description provided. Note that the return type [is an `enum`](https://time-rs.github.io/api/time/error/enum.Format.html), so you're able to match on the failure reason. Right now, the variants are for missing information — which you noted. This variant can't _currently_ be emitted when you're formatting an `OffsetDateTime` (but it's not guaranteed behavior). The one you'd be looking at for `Rfc2822` is the possibility of an invalid component. RFC2822 prohibits years before 1900, and as such returns an error in that situation. While not explicitly specified (iirc), offset seconds aren't included in the format, so an error is also emitted when this is the case.

For RFC2822, assuming that you're using a datetime that's recent or in the future, you should never encounter an error. No location on earth has had an offset as described for approximately 50 years (Liberia was the last to switch). The only _possible_ error that can be returned is an `io::Error`, which shouldn't be encountered under normal circumstances — it's basically if writing to the buffer itself fails.

**Comment by dbanty** [comment]
Thanks for such a detailed response! I didn't even think to look at the return type to see all the reasons it can fail 😅.

For context, I'm trying to replace [`chrono::DateTime::to_rfc2822`](https://docs.rs/chrono/latest/chrono/struct.DateTime.html#method.to_rfc2822) calls with direct `time` usages, and that chrono method simply returns a String. Sounds like there's a good reason for it not to though!
