### ISSUE TITLE
Provide a serde serializer / deserializer for Date

### ISSUE THREAD

**Issue by happysalada** [time-rs/time#447]
Does it make sense to provide a serializer and deserializer for the date struct ?
Rf3339 is only for OffsetDateTime, I'm not sure exactly what would be the name but format_description::parse("[year]-[month]-[day]") which I think is the most common format ? (corresponding to the date part of the rfc3339 format)

**Comment by jhpratt** [comment]
Unless there's a widely used specification (typically an RFC) that has this format, it won't be done. The macro already handles it with ease, and will be able to be used for serde purposes once I get around to reviewing the open PRs. Merely being _part_ of a format (such as RFC3339) is insufficient.

**Comment by happysalada** [comment]
That makes sense. I've seen that custom format PR, looking forward to it.
Thank you for the great software and the quick response time!
