### ISSUE TITLE
Special parsing

### ISSUE THREAD

**Issue by Yuri6037** [time-rs/time#448]
Some parsing functions are missing from time-rs to support https://github.com/Yuri6037/time-tz/issues/2:
- A Date::from_julian_day2(y, n) with n going from 1 - 365 excluding leap years and y again the year number (ex 2022).
- A Date::from_julian_day_allow_leap_years(y, n) with n going from 0-365 (which also allows counting for leap years) with y the year number (ex 2022).
- A Date::from_posix(m, n, d, y) where m is the month number in [1; 12], n is the week number in [1; 5] and d is the day of the week number from 0-6 with 0 = Sunday and y the year number (ex 2022).

Should these functions be part of the core time-rs crate or should they be implemented as part of time-tz?

EDIT: just seen from_ordinal_date so that means I only need a Date::from_ordinal_date_disallow_leap_years which still takes both year and ordinal but ignores leap years.

**Comment by jhpratt** [comment]
What do you mean by "excluding leap years"?

For `from_posix`, where would this be used? Would it be widespread? What is the week number in reference to?

**Comment by Yuri6037** [comment]
> What do you mean by "excluding leap years"?

Basically ignore leap years as defined in https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html#tag_08_03 (quote: `That is, in all years-including leap years-February 28 is day 59 and March 1 is day 60`)

> For `from_posix`, where would this be used? Would it be widespread? What is the week number in reference to?

This is basically the format `Mm.n.d` given in https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html#tag_08_03. Basically the format gives you the month number in the year (1 to 12), the week number from 1 to 5 and the day number in the week from 0 to 6 with 0 matching Sunday; and I need to construct a Date from this representation with the additional year number that I compute...

**Comment by jhpratt** [comment]
Ah, you want to use these when parsing the tzdb format? Realistically, this will eventually be done in `time` proper, but I don't have any algorithms to make this more efficient than a naïve implementation. So I think at this point in time, it would be best to keep it contained to `time-tz` because that's the primary use case.

**Comment by Yuri6037** [comment]
I've resolved the problem on my side using a combination of from_ordinal_date and from_iso_date
