### ISSUE TITLE
Surprising behavior of datetime macro

### ISSUE THREAD

**Issue by Yuri6037** [time-rs/time#449]
Consider the following code:

```rust
use time::macros::{datetime, offset};

fn main()
{
    let odt1 = datetime!(2021-07-01 12:0:0 UTC).to_offset(offset!(+1));
    let odt2 = datetime!(2021-07-01 12:0:0 +1);
    assert_eq!(odt1, odt2);
}
```

That code will fail in assert due to incorrect hour number. Somehow the hours value was changed from 12 to 11. Is this expected behavior? If this is expected, can this be documented?

Link to playground for testing: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=01a895353eee9011a759cc3beac71598

**Comment by jhpratt** [comment]
`odt1` creates a value that is noon in UTC, then converts it to UTC+1. This does not change the moment in time.  `odt2` creates a value that is noon in UTC+1. This is equivalent to 11:00 in UTC, which is what is stored internally. This behavior is correct. The `.to_offset(_)` call has no effect on equality, as it only changes the _appearance_, not the underlying moment.

**Comment by Yuri6037** [comment]
You could have documented that behavior because it still looks very surprising considering that it records both offset to +1 and sets hour value to 11...

**Comment by jhpratt** [comment]
That's because the debug representation shows the internal value. Notice that the time is part of the `utc_datetime` field. If you call `.hour()` on the value, you will still get 12.

> This would have been clearer if it returned a UTC OffsetDateTime with 11:00 but in this case it returned a OffsetDateTime +1 offset with 11:00 which is what is very surprising.

Why is it surprising? You explicitly requested the time 12:00 in the offset of UTC+1.

**Comment by Yuri6037** [comment]
> That's because the debug representation shows the internal value. Notice that the time is part of the `utc_datetime` field. If you call `.hour()` on the value, you will still get 12.

Ok that makes it more clear but I think this should be documented to avoid future users falling in the same trap of observing with Debug or assert_eq...
