### ISSUE TITLE
Add strftime/strptime support?

### ISSUE THREAD

**Issue by Jake-Shadle** [time-rs/time#450]
I've been removing all dependencies on `chrono` since it is unmaintained and using this crate instead where it makes sense, but one big difference between `chrono` and `time` is that time has its own format specifiers, which, while nicer, means that `time` can't be easily swapped in in cases where the `chrono` format specifiers were relied upon, for example

- https://github.com/cobalt-org/liquid-rust/issues/446

I've opened https://github.com/cobalt-org/liquid-rust/pull/460 to resolve https://github.com/cobalt-org/liquid-rust/issues/446, which implements the strftime part since that is all that liquid needs to replace `chrono`, but I think it makes sense to add this support to `time` itself so that any other projects can more easily drop `chrono` and use `time`.

**Comment by jhpratt** [comment]
Please search before opening a new issue.

**Comment by evanxg852000** [comment]
This was closed as duplicated, but without any link to the original issue and how it was solved. I got here looking for `strptime`. It seems this crate use to provide this and I don't know why it was removed.

**Comment by Jake-Shadle** [comment]
#341
