### ISSUE TITLE
time::OffsetDateTime::now_local() error: The system's UTC offset could not be determined

### ISSUE THREAD

**Issue by tubzby** [time-rs/time#457]
Version: time = { version = "0.3", features = ["local-offset"] }
OS: Mac OS Monterey 12.3

```
// result in error: failed to get OffsetDateTime
let t = time::OffsetDateTime::now_local();

```

**Comment by jhpratt** [comment]
Is the program multi-threaded at the time of invocation?

**Comment by tubzby** [comment]
Yes, I'm using tokio 1.0.

**Comment by jhpratt** [comment]
That's why. On POSIX systems, the method would be unsound if it returned a success value.

**Comment by tubzby** [comment]
Is there any document linked to this kind of behavior?

**Comment by jhpratt** [comment]
#293

**Comment by AlephAlpha** [comment]
@jhpratt If it only works in single-threaded programs, please say it in the doc.

**Comment by jhpratt** [comment]
_Any_ behavior is not guaranteed. Adding it to documentation would de facto guarantee that an error is returned when multi-threaded. Keep in mind that a `Result` is returned for a reason, and should always be handled. There is no guarantee that the method will succeed even when single-threaded.
