### ISSUE TITLE
Alternative, concise `Display` format for `Duration`

### ISSUE THREAD

**Issue by abonander** [time-rs/time#467]
While the current printouts for `Duration` are _precise_, they're not entirely pleasant to read:

```rust
println!("{}", time::Duration::new(123456, 789011223))
```

```
1d10h17m36s789ms11µs223ns
```

The lack of spacing probably doesn't help, but I think the main issue is that there's just too much information. 

For applications where conciseness is preferred, I suggest supporting the precision format specifier that prints only the largest nonzero field plus the given precision as a number of fractional digits, e.g.:

```rust
println!("{:.3}", time::Duration::new(123456, 789011223));
```

```
1.429d
```

**Comment by jhpratt** [comment]
I would accept a PR implementing this. It would need to use the [`Formatter::precision`](https://doc.rust-lang.org/stable/std/fmt/struct.Formatter.html#method.precision) method.
