### ISSUE TITLE
Add `InfinteFuture` and `InfinitePast` datetimes

### ISSUE THREAD

**Issue by vriesk** [time-rs/time#474]
They come very handy at times when code logic wants a value that will always be before/after any date in the system.

**Comment by jhpratt** [comment]
What's wrong with `Date::MAX` and `Date::MIN`?

**Comment by vriesk** [comment]
They're certainly usable in that way, but:
 - They will panic if any Duration is added/removed from them, making them unsafe to use directly
 - They are not "stable", depending on the large dates toggle
 - They will look like some arbitrary date when serialized, instead of possibly something more explanative like "InfinitePast" and "InfiniteFuture"

**Comment by vriesk** [comment]
(and to clarify - I know the `saturated_*` methods exist, however they are probably not commonly used as most people don't expect to be anywhere near any kind of limits and just use standard `+` and `-` operators)

**Comment by jhpratt** [comment]
What is the desired use case for this? I understand what you're saying, but I don't understand _why_.
