### ISSUE TITLE
FR: Implement subsecond rounding

### ISSUE THREAD

**Issue by vriesk** [time-rs/time#475]
This would be the equivalent of `chrono`'s https://docs.rs/chrono/latest/chrono/trait.SubsecRound.html

I imagine this could look like `.replace_nanosecond_with_precision()` method on Offset/PrimitiveDateTime

WDYT?

**Comment by jhpratt** [comment]
This was requested in #426, and is why the `replace_*` methods were introduced. You can round to your heart's desire using those methods.
