### ISSUE TITLE
Edition update without proper semver bump breaks downstream consumers

### ISSUE THREAD

**Issue by bahamat** [time-rs/time#484]
I've got a few projects using compiler 1.40 that have transitive dependencies on time. Up until a few days ago everything compiled fine, but now all of my builds are broken on time@0.3.11 with the following error:

```
error: failed to download `time v0.3.11`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/root/.cargo/registry/src/github.com-1ecc6299db9ec823/time-0.3.11/Cargo.toml`

Caused by:
  failed to parse the `edition` key

Caused by:
  supported edition values are `2015` or `2018`, but `2021` is unknown
```

If 2021 edition is actually required, that's a breaking change for the 0.3 series, and should be bumped to 0.4. Additionally, 0.3.10 and 0.3.11 should be yanked from crates.io so that transitive downstream consumers are not permanently broken.

**Comment by jhpratt** [comment]
Time 0.3 has _never_ supported Rust 1.40. The MSRV for 0.3.0 was 1.48 ([reference](https://github.com/time-rs/time/tree/v0.3.0) and [changelog](https://github.com/time-rs/time/blob/v0.3.0/CHANGELOG.md#changed)).

Further, bumping the minimum supported Rust version is not considered a breaking change. This view is widely held throughout the Rust ecosystem. This section has been present in the README since November 2020:

> The time crate is guaranteed to compile with any release of rustc from the past six months. Optional feature flags that enable interoperability with third-party crates (e.g. rand) follow the policy of that crate if stricter.

**Comment by newpavlov** [comment]
@jhpratt 
`time v0.3.14` has broke MSRV contract of the `der` crate. What feature should we enable to preserve the old MSRV? I couldn't find it by looking at `time`'s Cargo.toml.

**Comment by jhpratt** [comment]
There is no feature flag to lower the MSRV. Having this would necessitate removing features with a flag, which is not how cargo is supposed to work.

> P.S.: I would strongly prefer if foundational crates were more conservative in this regard...

`time`'s policy has been clearly stated for years. I may not always bump as soon as allowed by the policy, but I regularly bump the MSRV to take advantage of new features. I will note that I do **not** bump the MSRV solely for internal improvements, but only for improvements to end users.

As to the length of the policy, six months is typical, even for foundational crates. Why would someone need to use a compiler that is more than six months old? Upgrading a compiler twice a year seems more than reasonable.

**Comment by newpavlov** [comment]
>Why would someone need to use a compiler that is more than six months old?

The most obvious example is someone who uses Rust supplied by stable Debian. Also sometimes in industry you have no choice but to use an older toolchain (I had such unfortunate experience once...). It's one of the reasons why I wrote the MSRV RFC. You can work around it by tweaking Cargo.lock, but it's fairly unpleasant experience which does not add points for Rust.

**Comment by jhpratt** [comment]
I don't have a link off-hand, but I recall a survey showing that the overwhelming majority of people use rustup to download Rust, not using the OS-supplied version.

With regard to industry, why is upgrading twice per year not an option? I am open to lengthening the MSRV timeframe somewhat, but I'm skeptical. In my experience all it does is delay useful upgrades for downstream users.

**Comment by newpavlov** [comment]
I agree that people who have to use older toolchains are minority, but such people do exist. Also note that people may use different toolchains in different context.

>With regard to industry, why is upgrading twice per year not an option? I am open to lengthening the MSRV timeframe somewhat, but I'm skeptical.

In my case it was variation of the OS-supplied toolchain. We had a certified distribution, software was certified to run on it and must be compiled using OS-supplied software only in offline mode (of course, all dependencies were vendored). Downloading random toolchains from Internet was a complete nonstarter.

I am not against bumping MSRV per se. My problem is with MSRV bumps breaking downstream builds dependent on older toolchains on `cargo update`. `rust-version` and dependency resolution dependent on it should resolve this issue eventually, but we are not there yet.

**Comment by jhpratt** [comment]
> In my case it was variation of the OS-supplied toolchain. We had a certified distribution, software was certified to run on it and must be compiled using OS-supplied software only in offline mode (of course, all dependencies were vendored). Downloading random toolchains from Internet was a complete nonstarter.

How often is the Rust toolchain updated in your situation? Or others that are similar.

> `rust-version` and dependency resolution dependent on it should resolve this issue eventually, but we are not there yet.

:crossed_fingers: even though I don't believe anyone is actively working on it
