### ISSUE TITLE
WASM build always assumes wasm-bindgen is used

### ISSUE THREAD

**Issue by sagacity** [time-rs/time#496]
https://github.com/time-rs/time/pull/491 was merged and released as part of `0.3.12`. However, this means that the WASM build now assumes `wasm-bindgen` is being used.

We are doing a WASM build without `wasm-bindgen` (we are using our own binding generator, [fp-bindgen](https://github.com/fiberplane/fp-bindgen)). Because of this, our WASM project that has a dependency on `time 0.3.12` cannot be instantiated. `0.3.11` worked fine.

I believe this would also mean that a `no-std` WASM build using `time` will not work anymore. Perhaps the dependency on `js-sys` (and therefore `wasm-bindgen`) can be placed behind a feature flag?

**Comment by xy2iii** [comment]
Hi Roy, apologies for the breakage. [PR up](https://github.com/time-rs/time/pull/499).

fp-bindgen looks much more flexible than wasm-bindgen. If we can do some sort of integration to make your life easier, please let us know :wink:

**Comment by sagacity** [comment]
Thanks so much, especially for the quick turnaround. I'm not sure if we need any extra integration at this point but I'll ask around 😄

**Comment by jhpratt** [comment]
Thanks for the PR @xy2iii.

I'll take a look at this in the coming days, likely Sunday or Monday. It's soon enough after the latest release that I'm not concerned about this technically being breakage. One could argue it's a bug fix because it breaks `#![no_std]` releases.

**Comment by stevelr** [comment]
Agree - I agree it's a bug not an enhancement. 0.3.12 was a breaking change for wasm builds that don't use wasm-bindgen, including most server-side wasm frameworks. PR https://github.com/time-rs/time/pull/499 looks like it will fix it.

**Comment by jhpratt** [comment]
Fixed in #499.

**Comment by stevelr** [comment]
Thanks!
