### ISSUE TITLE
Display trait implementation for time::Time incorrectly trims the zeros from the sub-second part

### ISSUE THREAD

**Issue by vartiait2** [time-rs/time#508]
Hi,

I noticed that when logging timestamps with OffsetDateTime, sometimes the sub-second parts seemed not to be in order.

E.g.

```
2022-09-20 11:46:05.674944 +00:00:00 <log message>
2022-09-20 11:46:05.67616 +00:00:00 <log message>
2022-09-20 11:46:05.677763 +00:00:00 <log message>
```

Tracing this back to Display trait implementation of time::Time, where 
trimming zeros off from the sub-second part unintentionally decreases the magnitude of the sub-second part

https://github.com/time-rs/time/blob/f44c540563727049a4b90b506f68636f745876da/src/time.rs#L641

As an example, a following test will fail with the current Display trait implementation.

```rust
#[test]
fn display() {
    assert_eq!(time!(0:00:00.676_160).to_string().as_str(), "0:00:00.676160");
}
```

BR,
Tuure

**Comment by jhpratt** [comment]
There is no guarantee of the length of the output. The code that you found is precisely what shortens it — the fewest digits needed are used. This does not "decrease the magnitude" of the value, as trailing zeroes after a decimal point are unnecessary.

I will note that if it was always output with the same width, you would be seeing nine digits, not six, as that is the precision that the value is stored with. And you would probably be wondering why there was always `000` at the end.
