### ISSUE TITLE
`Duration::subsec_nanoseconds` can sometimes be out of range

### ISSUE THREAD

**Issue by CryZe** [time-rs/time#514]
My code calling `Duration::subsec_nanoseconds` has an assertion that the nanoseconds returned by this function are indeed within the given range... and the assertion triggered. Unfortunately, I haven't been able to reproduce it yet as this could almost even be a 1 in a billion chance of this even happening. I'll update this issue as I find out more.

**Comment by jhpratt** [comment]
Definitely try to reproduce if possible. Even a large reproduction is better than nothing.

On my end I need to add debug assertions in methods like this one. Better than relying on users like yourself to add assertions.

**Comment by CryZe** [comment]
Nvm, the bug was something else. The value was out of range AFTER I casted it to u32, which I did after negating it if it's negative... but I only checked the seconds in my condition, which is insufficient, as 0 seconds and -100 nanoseconds for example would be a positive seconds value, but a negative nanoseconds value. Interestingly this invariant here at least doesn't mention that edge case: https://docs.rs/time/latest/src/time/duration.rs.html#38

**Comment by jhpratt** [comment]
Okay! I still need to add debug assertions regardless :slightly_smiling_face: 

For clarity, the signs always match…when there is a sign. If seconds is zero, then it doesn't have a sign, so the nanoseconds is what determines it. There are `is_positive` and `is_negative` methods if that works for your use case.

**Comment by CryZe** [comment]
Yeah I'll look into incorporating those. Thanks for the help.
