### ISSUE TITLE
`Duration` between two `DateTime`s.

### ISSUE THREAD

**Issue by reitermarkus** [time-rs/time#536]
Currently it seems that only `Instant::elapsed` provides a way to get a `Duration`, but there is no way to get a `Duration` between two `OffsetDateTime`s.

**Comment by CryZe** [comment]
You can just subtract them.

**Comment by jhpratt** [comment]
Yeah, subtracting them does the trick.

Leap seconds are a completely different story, and that won't be supported until the tzdb is integrated. That's something I have not done any actual work on, only some thinking about how I want the API to look.

**Comment by reitermarkus** [comment]
> Yeah, subtracting them does the trick.

That's what I tried, but I see my problem. It does not work in `const` context, e.g.

```rust
const GPS_EPOCH: OffsetDateTime = datetime!(1980-01-06 00:00 UTC);
const GPS_TO_UNIX_TIME_OFFSET: time::Duration = OffsetDateTime::UNIX_EPOCH - GPS_EPOCH;
```

> I have a branch that takes leap seconds into account, but that's probably a separate issue to discuss.

This would probably also be beneficial for my use case.

**Comment by jhpratt** [comment]
That's because trait implementations cannot currently be const. Once they can, it is almost certain that I will constify that and many others. It doesn't mean that the trait isn't currently implemented.

**Comment by reitermarkus** [comment]
Yeah, the error message is actually quite clear after reading it the second time:

```
the trait `Sub<_>` is implemented for `OffsetDateTime`, but that implementation is not `const`
```

**Comment by jhpratt** [comment]
That's actually a significant improvement than it was last time I was playing around with const traits on nightly. It used to be _far_ more confusing.
