### ISSUE TITLE
Weekday from number

### ISSUE THREAD

**Issue by Kinrany** [time-rs/time#542]
Currently weekdays can be converted to numbers, with four options: zero-based/one-based and sunday-based/monday-based.

It would be convenient to have the reverse constructors: from a zero-based or one-based offset, for a sunday-based or monday-based week, create a Weekday value.

**Comment by jhpratt** [comment]
This is definitely doable with minimal effort. Once I get to documenting features that are on `main` and cut a release, I can do this quite quickly.

**Comment by Kinrany** [comment]
I can probably help with a PR. Unless it's easier for you to just do it compared to reviewing code later.

**Comment by jhpratt** [comment]
Up to you! Either way it will be in a separate release.
