### ISSUE TITLE
implement `std::iter::Step` for `time::Date`

### ISSUE THREAD

**Issue by emilioziniades** [time-rs/time#585]
It would be nice to do something like
```rust
let start_date = date!(2023 - 01 - 01);
let end_date = date!(2023 - 06 - 01);
for date in start_date..end_date {
    println!("{date}");
}
```

I naively tried this and got the following compiler error: "the trait `Step` is not implemented for `time::Date`"

Having a look at [`std::iter::Step`](https://doc.rust-lang.org/std/iter/trait.Step.html), it looks pretty straightforward to implement.

If this is something worth doing, I'd be happy to throw together a quick PR.

**Comment by emilioziniades** [comment]
Nevermind, I didn't see that `Step` has not been stabilized yet. I am using stable rust, but for some reason the compiler refers to `Step`. Here's an [example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=ff49f254d7942c43178e644131cc5e34)

**Comment by jhpratt** [comment]
The compiler refers to it because it's still used internally there. I assure you that it will implement `Step` once it's stable! It's one of a number of features I'm tracking, and one I have actually put in some work to get closer to stabilization.

**Comment by emilioziniades** [comment]
Ah okay cool, thanks for getting back to me. It's a neat trait and looking forward to it being stabilised.
