### ISSUE TITLE
Allow custom visibility modifier for generated module

### ISSUE THREAD

**Issue by nui** [time-rs/time#597]
`time::serde::format_description` always generate module without visibility modifier. Would it be possible to add support for this functionality? I see no reason why it have to be private module only.

I want to declare module in private module and publicly re export it but Rust doesn't allow re-exporting private items.

related link:
https://docs.rs/time/latest/time/serde/macro.format_description.html

**Comment by jhpratt** [comment]
Why is it desired to re-export the module?

**Comment by nui** [comment]
> Why is it desired to re-export the module?

I actually don't need re exporting.

Let say if this module is under `crate::serde` I couldn't use it from `crate::app::handler` because this module is private inside `crate::serde` module by current generated output.

**Comment by jhpratt** [comment]
If you want to be able to use it anywhere in the crate, it needs to be at the root level of the crate. That's the same as any other module, and is trivially done with the existing macro.
