### ISSUE TITLE
Switch from `winapi` to `windows-sys`

### ISSUE THREAD

**Issue by jhpratt** [time-rs/time#609]
`winapi` appears unmaintained and `windows-sys` is a crate provided by Microsoft. `time` should switch for that reason.

If anyone has the requisite knowledge, feel free to open a PR. I won't get to this in the next couple weeks, and even then may not be able to implement the change.

**Comment by Yuri6037** [comment]
I recommend actually using windows-sys (this is what I'm using btw) which has a smaller footprint than windows-rs as this crate probably just needs some very specific Win32 functions (like GetSystemTime).

**Comment by jhpratt** [comment]
Looks like the `windows-rs` repo is published as the `windows-sys` crate. So `windows-sys` is in fact what I was looking at when I made the issue.

**Comment by complexspaces** [comment]
How many functions/constants does `time` use from the Win32 APIs? `windows-bindgen` might be the better option if its a very small number to avoid version churn and any MSRV headaches.

**Comment by jhpratt** [comment]
No reason. As I said above, I was looking at the _repository_. I haven't used Windows in almost a decade and have no feelings whatsoever on which crate to use (aside from it being maintained).

**Comment by jhpratt** [comment]
`windows-bindgen` had a release just a couple hours ago?

**Comment by Alexendoo** [comment]
Looks like standalone FFI calls that don't depend on `winapi` are already used - https://github.com/time-rs/time/blob/500f8e4517cb89f0aa80087130ed2f8b8349f162/time/src/sys/local_offset_at/windows.rs

**Comment by jhpratt** [comment]
Ha, I totally forgot that the dependency was removed a while back. `winapi` is nowhere to be found in current code. Closing.
