### ISSUE TITLE
`Weekday`  and `Time` (and probably more types) do not respect formatting flags

### ISSUE THREAD

**Issue by jrpear** [time-rs/time#626]
```rust
println!("{:>10}", time::Weekday::Monday);
```
Gives
```
Monday
```
It should give
```
    Monday
```

This is because `time`'s `Display` implementations don't look at the formatting flags on the Formatter passed.

[`fmt::Formatter::pad`](https://doc.rust-lang.org/std/fmt/struct.Formatter.html#method.pad) can do this automatically.

**Comment by jhpratt** [comment]
This can definitely be done. A quick look shows that `Weekday` will be trivial. `Time` will be slightly more involved, as I'll have to calculate the width up-front. The same is true for other types, I imagine.

**Comment by jhpratt** [comment]
Done on `main`.
