### ISSUE TITLE
Panic when `nth_next_occurrence` and `nth_prev_occurrence` get `n = 0`

### ISSUE THREAD

**Issue by phisch** [time-rs/time#629]
Both `nth_next_occurrence` and `nth_prev_occurrence` return a `time::Date`, but internally use a function that returns an `Option<Date>`.

This example causes a panic:
```rs
use time::{Date, Month};

fn main() {
    let date = Date::from_calendar_date(2023, Month::October, 16).unwrap();
    let nth_next = date.nth_next_occurrence(time::Weekday::Friday, 0);
}
```

## Why?

This is because [nth_next_occurrence](https://github.com/time-rs/time/blob/72f03e05073621f713dead88f16c227187afd6f9/time/src/date.rs#L679C6-L679C6) returns `Self` instead of `Option<Self>`:
```rs
pub const fn nth_next_occurrence(self, weekday: Weekday, n: u8) -> Self {
    expect_opt!(
        self.checked_nth_next_occurrence(weekday, n),
        "overflow calculating the next occurrence of a weekday"
    )
}
```
while using [checked_nth_next_occurence](https://github.com/time-rs/time/blob/72f03e05073621f713dead88f16c227187afd6f9/time/src/date.rs#L945-L952) which returns `Option<Self>`:
```rs
pub(crate) const fn checked_nth_next_occurrence(self, weekday: Weekday, n: u8) -> Option<Self> {
    if n == 0 {
        return None;
    }

    const_try_opt!(self.checked_next_occurrence(weekday))
        .checked_add(Duration::weeks(n as i64 - 1))
}
```

Both functions should return `Option<Self>`.

**Comment by jhpratt** [comment]
The panicking behavior is documented, and changing the return type is a breaking change.
