### ISSUE TITLE
Implement `arbitrary::Arbitrary` trait for exported types

### ISSUE THREAD

**Issue by OrangeTux** [time-rs/time#642]
First of all, thanks for this library!

I'm adding support for fuzzing to a private project of mine. That requires me to implement the [`arbitrary::Arbitrary`](https://docs.rs/arbitrary/1.3.2/arbitrary/trait.Arbitrary.html) (a crate maintained by the [rust-fuzz organisation](https://github.com/rust-fuzz)) manually for a few types of this library.  I'm happy to upstream these changes into this project. Are you interested?

This library implements the [`quickcheck::Arbitrary`](https://docs.rs/quickcheck/latest/quickcheck/trait.Arbitrary.html) trait for a few exported types. I'm thinking to implement `arbitrary::Arbitrary` for all types that implement `quickcheck::Arbitrary`.

You can find my current progress in t[he branch 'arbitrary-support'](https://github.com/OrangeTux/time/tree/arbitrary-support) of my fork.

**Comment by jhpratt** [comment]
I previously addressed this in #502. I was open to it as part of #549, but that never happened for some reason.

**Comment by OrangeTux** [comment]
Thanks for linking to those tickets. It's a pity that #549 is stalled. I read through the issue, but I fail to understand the discussion. Therefore, I can't take over  #549 and move it forward. 

I'll close this issue
