### ISSUE TITLE
ISO6801 and a SPACE instead of a T

### ISSUE THREAD

**Issue by eyyyyyyy3** [time-rs/time#644]
Hello. According to the ISO 6801 standard the T doesn't have to be there it can also be replaced by a space.

I mean the linked page in the wiki has a example of the ISO8601 standard with a space instead of a T.
[THE ISO STANDARD IN QUESTION](https://www.iso.org/iso-8601-date-and-time-format.html)
`For example, September 27, 2022 at 6 p.m. is represented as 2022-09-27 18:00:00.000.`

## Wikipedia
> A single point in time can be represented by concatenating a complete date expression, the letter "T" as a delimiter, and a valid time expression. For example, "2007-04-05T14:30". In ISO 8601:2004 it was permitted to omit the "T" character by mutual agreement as in "200704051430",[[37]](https://en.wikipedia.org/wiki/ISO_8601#cite_note-37) but this provision was removed in ISO 8601-1:2019. Separating date and time parts with other characters such as space is not allowed in ISO 8601, but allowed in its profile RFC 3339.[[38]](https://en.wikipedia.org/wiki/ISO_8601#cite_note-38)

It kinda seems that the people who write the standards don't know what they're doing themselves but it would be nice if we could also have that option to parse a with a space instead of a T that is.

As a final argument for it's implementation, postgresql also supports the with a space version in its timestamptz type.

If I have missed a function that does what I have described sorry for wasting your time XD. (where can i find it)

**Comment by eyyyyyyy3** [comment]
This is really similar to #595

**Comment by jhpratt** [comment]
Given that you've already found that issue, you'll see in it that the specification does not permit a space.
