### ISSUE TITLE
reliable way to get local time

### ISSUE THREAD

**Issue by kzhui125** [time-rs/time#645]
Recently I try to switch `chrono` to `time-rs`. But I don't find a reliable way to get local datetime. (macOS)

Why doesn't `time-rs` implement `local time` like `chrono` does? including multiple thread environment.

<img width="731" alt="image" src="https://github.com/time-rs/time/assets/11925432/46d162b0-a646-4330-ad6a-1f57151e0d7d">

```rs
#[tokio::main]
async fn main() {
    let now = chrono::Local::now();
    println!("{now}");

    let is_err = time::OffsetDateTime::now_local().is_err();
    println!("{is_err}");
}
```

Maybe I have to switch back to `chrono` to get local time.

**Comment by kzhui125** [comment]
I want a local time function that won't fail...

**Comment by jhpratt** [comment]
Last I checked, `chrono` implements it in a way that is both expensive and unsound. `time` does what is necessary to avoid unsoundness. This has been addressed in multiple issues previously.
