### ISSUE TITLE
local-offset feature is leaking memory on Apple platforms

### ISSUE THREAD

**Issue by aw-cf** [time-rs/time#651]
This report is mainly an FYI to let you know about an issue in one of the dependencies used for the `local-offset` feature.

This call to `num_threads::is_single_threaded()` is leaking memory on macOS.
https://github.com/time-rs/time/blob/be932d86ca64b2725b03271cd3c66834be0ee8d0/time/src/sys/local_offset_at/unix.rs#L144

https://github.com/jhpratt/num_threads/issues/16 has details on the issue and was introduced with version `0.1.4`.

**Comment by jhpratt** [comment]
Not a bug here. I'm the maintainer of both crates.
