### ISSUE TITLE
Implement `FromStr` for `PrimitiveDateTime` and `OffsetDateTime`

### ISSUE THREAD

**Issue by ogarcia** [time-rs/time#668]
It would be very interesting if `FromStr` were implemented for `PrimitiveDateTime` and `OffsetDateTime`. The [RFC3339 format](https://datatracker.ietf.org/doc/html/rfc3339) could be used as a reference for the input string since it is usually the most used.

For `PrimitiveDateTime` same format can used but without the timezone information: `%Y-%m-%dT%H:%M:%S%.f`.

**Comment by jhpratt** [comment]
This is not planned. Using `T::parse(value, &Rfc3339)` is clearer as it shows the format that is expected. Note that `Date` and `Time` don't even implement `FromStr` — `Month` and `Weekday` are the only types that do.
