### ISSUE TITLE
Mark the date_time function from OffsetDateTime as public

### ISSUE THREAD

**Issue by samrg472** [time-rs/time#673]
Hello,

At present, the best way to convert an `OffsetDateTime` to `PrimitiveDateTime` is to use the `new` function and construct it from parts. If `OffsetDateTime::date_time` was public, the conversion below wouldn't be necessary.

I use `PrimitiveDateTime` for database storage where columns are typically stored without a timezone for UTC.

```rust
let now = OffsetDateTime::now_utc();
let primitive = PrimitiveDateTime::new(now.date(), now.time());
```

**Comment by jhpratt** [comment]
#369
#390
#395
#454
#458
#553
#658
