### ISSUE TITLE
Confusing deprecation message for `time::Instant`

### ISSUE THREAD

**Issue by johnbatty** [time-rs/time#677]
`time::Instant` was deprecated in 0.3.35:
https://github.com/time-rs/time/issues/650

The deprecation error message displayed by clippy is:
```
error: use of deprecated struct `time::Instant`: import `time::ext::InstantExt` instead
```

This is confusing advice, as the primary fix is to use `std::time::Instant` rather than `time::Instant`.  It took me a while to figure this out. 
 There are some additional extension methods defined in `time::ext::InstantExt`, but these won't be required by most users.

I suggest that the error is changed to:
```
error: use of deprecated struct `time::Instant`: import `std::time::Instant` instead
```

**Comment by jhpratt** [comment]
I'm open to changing the deprecation message, but my initial thought is why you're using `time::Instant` instead of `std::time::Instant` if you're not using any of the additional interoperability `time` provides? It is otherwise a trivial wrapper struct.

**Comment by jhpratt** [comment]
The deprecation message has been changed on `main`.
