### ISSUE TITLE
Formatting bug on ISO8601

### ISSUE THREAD

**Issue by dracarys18** [time-rs/time#678]
Hi @jhpratt continuing our discussion from #674. I have created a repo to reproduce this bug [here](https://github.com/dracarys18/reproduce_time_bug). You can try to run it and check it yourself.

```bash
cargo r | tee test.txt
cat test.txt | rg ":60."
```

This looks like this happens only when the TimePrecision is 3 here.

```rust
    const FORMAT_CONFIG: EncodedConfig = Config::DEFAULT
        .set_time_precision(TimePrecision::Second {
            decimal_digits: NonZeroU8::new(3),
        })
        .encode();
```

It looks like it's rounding off the time to 60 seconds and it's happening every minute. If I change the precision to 6 I can see it's adjusting to nano second

**Comment by jhpratt** [comment]
Odd. I've confirmed that the code as-is does what you say, so I'll definitely look into this more.

**Comment by jhpratt** [comment]
> It looks like it's rounding off the time to 60 seconds and it's happening every minute.

Confirmed. This appears to be the behavior of `Display` for floats, and to be fair it is what 99.9% of people would expect (as it's the closest to the true value). I naïvely assumed that it would truncate, and a quick search just now reveals that the behavior isn't actually documented.

Given that I can't rely on the standard library's implementations here, I'm going to have to manually format floats. It's doable and I'll probably get to it this weekend.

**Comment by dracarys18** [comment]
> > It looks like it's rounding off the time to 60 seconds and it's happening every minute.
> 
> Confirmed. This appears to be the behavior of `Display` for floats, and to be fair it is what 99.9% of people would expect (as it's the closest to the true value). I naïvely assumed that it would truncate, and a quick search just now reveals that the behavior isn't actually documented.
> 
> Given that I can't rely on the standard library's implementations here, I'm going to have to manually format floats. It's doable and I'll probably get to it this weekend.

Sure @jhpratt, I can take this up if you just give me a place where I should start looking at.

**Comment by jhpratt** [comment]
The specific function is `format_float` in `src/formatting/mod.rs`. The `Some` arm is what is relevant.

**Comment by dracarys18** [comment]
> The specific function is `format_float` in `src/formatting/mod.rs`. The `Some` arm is what is relevant.

Sure I will take a look and create a PR for this. Thanks!

**Comment by dracarys18** [comment]
I went into this rabbit whole and [here](https://github.com/rust-lang/rust/blob/a61b14d15e4a742fb9d117d089626f5275a286c4/library/core/src/num/flt2dec/strategy/grisu.rs#L529) can see they round off the numbers if numbers after decimal is more than the limit. A [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=f2e090b64b968af32838e0ec79ac4b60) to check that as well.

**Comment by dracarys18** [comment]
Hey @jhpratt, I have handled it in a way like truncate the float before we format it. [Playground link for it](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=1bbf848d7e3c048b87dc1da92fa31c26). This would require just a one like change in `format_float` function where we would just truncate `value` before it we pass it in `write!`. Let me know if you have better suggestions, Otherwise I will create a PR for this.
