### ISSUE TITLE
Ferrocene compiler needs more information about the type of Box<_> at compile time.

### ISSUE THREAD

**Issue by benracine** [time-rs/time#689]
When attempting to compile this crate using the Ferrocene compiler, I see the following error in `/src/format_description/parse/mod.rs`. 

![image](https://github.com/time-rs/time/assets/798971/de308ef9-7c36-4f20-a6c1-9e0228372936)

**Comment by jhpratt** [comment]
This isn't specific to Ferrocene, nor is it an issue at all. See #681 — it's already been fixed.
