### ISSUE TITLE
error[E0282]: type annotations needed for `Box<_>`

### ISSUE THREAD

**Issue by gc-victor** [time-rs/time#693]
After updating Rust to version 1.8.0, the following error appears:

```
error[E0282]: type annotations needed for `Box<_>`
  --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.34/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++

For more information about this error, try `rustc --explain E0282`
```

**Comment by the-emerald** [comment]
Updating `time` to 0.3.36 (from 0.3.34) fixed it for me!

**Comment by Mouwrice** [comment]
> Updating `time` to 0.3.36 (from 0.3.34) fixed it for me!

Can confirm! Had the exact same situation and solution.

**Comment by jhpratt** [comment]
This was previous raised in #681, #685, and #689.

**Comment by liudonghua123** [comment]
I have the similar issues when build a tauri app on macos. It's strange that the tauri app build successfully on linux and macos, but not on macos.

I also noticed that it seems [`Compiling tao`](https://github.com/tauri-apps/tao) logging appears on macos building logs, but not on linux.

See https://github.com/liudonghua123/pxt-microbit-app/actions/runs/10517054766/job/29140512953.
