### ISSUE TITLE
Add what features should be enabled in docs

### ISSUE THREAD

**Issue by InAnYan** [time-rs/time#701]
Was annoyed when Rust compiler couldn't find `OffsetDateTime::parse` method, when it turns out it's only available when feature `parsing` enabled.

Typically, in documentation there is note like "available only with `parsing` feature", or something like that.

I suppose there are other places where there is no such note

**Comment by jhpratt** [comment]
On docs.rs, this is showing exactly as expected. On time-rs.github.io, the annotations aren't showing for some reason. I [just regenerated](https://github.com/time-rs/time/actions/runs/10234276447/job/28822610150) the docs in CI to no avail. I presume this goes back to the recent commit changing from `__time_03_docs` to `docsrs` for the cfg, but I'm unable to reproduce locally. Happy to accept a PR with the necessary changes.

**Comment by InAnYan** [comment]
Oh, I should've checked and mentioned that I used time-rs.github.io, sorry, yes :)

The problem is only on time-rs.github.io

**Comment by jhpratt** [comment]
Fixed! Basically, I forgot how I had my docs publishing set up. It's a bit convoluted due to the way I'm pulling in multiple repos.
