### ISSUE TITLE
date!() macro syntax gets messed up by rustfmt

### ISSUE THREAD

**Issue by kasparthommen** [time-rs/time#714]
Running `rustfmt` (i.e., `cargo fmt`) on

```rust
let d = date!(2024-10-23);
```

leads to

```rust
let d = date!(2024 - 10 - 23);
```
because `rustfmt` interprets the dashes as subtractions and adds spaces around them.

This is a problem that is inherent to `rustfmt`. Workarounds include using `#[rustfmt::skip]` and configuring `rustfmt` with the (nightly) `spaces_around_ranges` option, but these are not great. I wonder if it would be an option to permit alternative syntaxes for the `date!` macro? Ideas:
- `date!(2024.10.23)`  <-- my preference
- `date!(2024--10--23)`
- `date!(2024_10_23)`
- `date!(2024:10:23)`

**Comment by jhpratt** [comment]
Ultimately this is a `rustfmt` problem. My recommendation would be to use nightly `rustfmt` in combination with [`skip_macro_invocations=["date", "time", "offset"]`](https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=skip_macro#skip_macro_invocations). I've actually been meaning to do this for the `time` repo itself, so I'll likely do this shortly.
