### ISSUE TITLE
Compilation error: type annotations needed for `Box<_>`

### ISSUE THREAD

**Issue by sigurd4** [time-rs/time#717]
```
error[E0282]: type annotations needed for `Box<_>`
  --> /home/sigurd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.28/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
```
I guess wether or not you get away with type inference here depends on the rust version

**Comment by CryZe** [comment]
Run `cargo update` and then the issue is gone. This is a well known problem.

**Comment by sigurd4** [comment]
Tried it, and it didn't work.

Tried using both nightly and stable toolchains, same result.

I'm trying to install an aur package with this as a dependency, so it could be the install script needs to run `cargo update` for it to work.

But i did run that in the workspace folder `~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.28` and i can confirm that the install script installs in the same directory, and that running `cargo update` again after a new install attempt does not update the deps over again, suggesting the update didnt get reset when installing again.

Installing the package manually works fine, so i'll close this and re-open [abusch/sinuous#137](https://github.com/abusch/sinuous/issues/137).

**Comment by jhpratt** [comment]
Here I thought that unpinning an issue after _six months_ would have been sufficient…
