### ISSUE TITLE
Tests fail when not using --all-features

### ISSUE THREAD

**Issue by antoyo** [time-rs/time#719]
Hi.
When I run the test without `--all-features`, there's a failure:
```
---- time/src/offset_date_time.rs - offset_date_time::OffsetDateTime::checked_to_utc (line 262) stdout ----
error: invalid component: year was 999999
  --> time/src/offset_date_time.rs:273:15
   |
14 |     datetime!(+999999-12-31 23:59:59 -1).checked_to_utc(),
   |               ^^^^^^^
```

To make sure this doesn't happen, I guess it would be good to have at least a CI run without `--all-features`.

Thanks!

**Comment by zxsa89675** [comment]
Hello, we tried to solve the issue.

This is what we did:

This change adds a new job to the CI workflow that runs tests without the --all-features flag. This will help catch issues like the one described in the GitHub issue, where certain tests fail when not all features are enabled.

You can review changes in this commit: https://github.com/zxsa89675/time-rs-time-719/commit/bce4a7f31f2cf5c7c1c13a0a047a643af108acdb.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by jhpratt** [comment]
This is deliberate. Because features are additive, it's not worth the effort to properly gate everything in the tests. When `--all-features` is not passed, there is an unreachable code diagnostic output indicating that the flag is required _and_ a subprocess is spawned with that flag.
