### ISSUE TITLE
Rfc3339 parser allows invalid datetimes to be parsed.

### ISSUE THREAD

**Issue by Firstyear** [time-rs/time#720]
```
fn main() {

    let valid = OffsetDateTime::parse("2020-09-25T01:22:02+00:00", &Rfc3339)
        .unwrap();

    let invalid = OffsetDateTime::parse("2020-09-25 01:22:02+00:00", &Rfc3339)
        .unwrap_err();
}
```

https://datatracker.ietf.org/doc/html/rfc3339#section-5.6

Works in 3.36 but not 3.37. As I'm reading RFC3339, the T is required, and a space isn't valid.  `   date-time       = full-date "T" full-time`

**Comment by jhpratt** [comment]
See #700. The spec is not 100% clear, so I decided to go with the more lax parsing (while still only emitting `T`).
