### ISSUE TITLE
strptime does not populate all time::Tm fields

### ISSUE THREAD

**Issue by octplane** [time-rs/time#92]
This sample code does not what's expected:

```
extern crate time;
fn main() {

  let t = time::at(time::Timespec::new(236928791,113000000));
  let format = "%Y-%m-%d %T.%f";

  let witness = "1977-07-05 07:33:11.113000000";
  assert_eq!(time::strftime(format, &t).ok().unwrap(), witness);

  assert_eq!(time::strptime(witness.as_ref(), format).unwrap(), t);

}
```

I wonder if I'm doing something wrong or the library is behaving wrong... ?

**Comment by nerdrew** [comment]
I see something similar. `wday` and `yday` are not set when parsing a date.

**Comment by DoumanAsh** [comment]
Saw something similar with my attempts to parse time from log file:
```11/05/15 22:08:14``` becomes a proper Tm struct, but when i convert to timespec i get:
```Timespec { sec: -1708998706, nsec: 0 } ```

Due to that you cannot compare strptime() Tm with normally initialized ones.
But not sure how ```strptime`` should behave?

**Comment by willi-kappler** [comment]
Same here:

    extern crate time;

    use time::{strptime, Duration};

    fn main() {
        let t1 = strptime("2016-02-05 16:52:21", "%Y-%m-%d %H:%M:%S").unwrap();
        let t2 = strptime("2016-02-05 16:52:22", "%Y-%m-%d %H:%M:%S").unwrap();

        // This fails, because tm_wday and tm_yday are not set using strptime:
       assert_eq!(t1 + Duration::seconds(1), t2);

        // This runs as a work around:
        assert_eq!(t1 + Duration::seconds(1), t2 + Duration::seconds(0));
    }

Any news on that ?

I know `time` is deprecated and I'll move to `chrono` when I have more time.
(And `chrono` uses `time` internally ? At least there is a dependency in its `Cargo.toml`)

Thanks!
